### ISSUE TITLE
All data not selected when select all checkbox (on table header) is selected on lazy grid

### ISSUE THREAD

**Issue by mrth1995** [vaadin/flow-components#1145]
Hello, 

I have lazy load grid with multiple selection. When i do select all (by clicking checkbox on table header) data on row grid suppose to be selected like demo in this page: https://vaadin.com/components/vaadin-grid/java-examples/selection. But it's not.
Here is a piece of code and demo of the case.
![Screen-Recording-2020-03-19-at-20 51 40](https://user-images.githubusercontent.com/49490460/77074752-de0cc580-6a23-11ea-8e2b-b4428117633f.gif)

Here is code of Grid that implement lazy grid.
```
addColumn(Activity::getActivityName).setHeader(valueNameHeader);
addColumn(Activity::getRequestorId).setHeader("Requestor Name");
setSelectionMode(Grid.SelectionMode.MULTI);
addThemeVariants(GridVariant.LUMO_NO_BORDER,
GridVariant.LUMO_NO_ROW_BORDERS, GridVariant.LUMO_ROW_STRIPES);
asMultiSelect().addSelectionListener(multiSelectionEvent -> {
    LOG.info(multiSelectionEvent.getAllSelectedItems().toString());
});
((GridMultiSelectionModel<Activity>) getSelectionModel()).setSelectAllCheckboxVisibility(GridMultiSelectionModel.SelectAllCheckboxVisibility.VISIBLE);
```
here is code of lazy grid that fetch data.
```
public void load() {
        setPageSize(20);
        DataProvider<T, Map<String, Object>> dataProvider = DataProvider.fromFilteringCallbacks(
                query -> {
                    try {
                        List<T> result = getResult(createTableParam(query));
                        return result.stream();
                    } catch (Exception e) {
                        throw new RuntimeException(e);
                    }
                },
                query -> {
                    try {
                        CountResult result = getCountResult(createTableParam(query));
                        return result.getCount().intValue();
                    } catch (Exception e) {
                        throw new RuntimeException(e);
                    }
                }
        );
        ConfigurableFilterDataProvider filterDataProvider = dataProvider.withConfigurableFilter(
                (Void v, Map<String, Object> filterOutput) -> filterOutput);
        setDataProvider(filterDataProvider);
    }
```
I use ``Vaadin version 14.1.5``

**Comment by vursen** [comment]
Hey! Same as @tarekoraby, I wasn't able to reproduce the topic issue. I tried out Tarek's example with both using `DataProvider.fromCallbacks` and `DataProvider.fromFilteringCallbacks`, but the selection worked anyway.  

I'm closing the issue for now. @mrth1995 Feel free to re-open it with **clear minimal reproduction** if the issue is still reproducible for you.

> But I have strange behaviours, when I select all and then deselect by hand some records ,

@ado2000 Please, open a separate ticket with a minimal reproduction example that would demonstrate the issue.

**Comment by dominik42** [comment]
Just for the record and in case myself stumbled upon this issues in a few months again ...
As @ado2000 mentioned in the [Flow Discord channel](https://discord.com/channels/732335336448852018/774366825756229632/984027615629295648), a possible solution is to implement `equals` and `hashCode` for the DTO/Entity/POJOo you use in the grid.

**Comment by spalyukh-flex** [comment]
I had the same issue with Vaadin 23, but in my case, the reason was in missing the counter query... So, I've digged to the following method:

`com.vaadin.flow.component.grid.AbstractGridMultiSelectionModel#isSelectAllCheckboxVisible`

Where I did find the following clarification:

```java
case VISIBLE:
            // Don't show the Select All Checkbox for undefined size, even if
            // the visible property is chosen. Select All Checkbox's state
            // changing requires a size query, which is not expected for
            // undefined size
            return getGrid().getDataCommunicator().isDefinedSize();
``` 

So I simply added a counter query and everything started working as expected.

Here is an example of my config:

1. Enable multiselect:
```java
private void enableMultiSelectOption() {
      GridMultiSelectionModel<E> model = (GridMultiSelectionModel<E>) setSelectionMode(SelectionMode.MULTI);
      model.setSelectAllCheckboxVisibility(GridMultiSelectionModel.SelectAllCheckboxVisibility.VISIBLE);
 }
```
2. Set items and provide 2 queries: 

- For fetching data
- To count number of records

```java
    private void loadData() {
        grid.setItems(
                query -> memberService.findAllByFilter(memberFilterModel,
                        PageRequest.of(query.getPage(),
                                query.getPageSize(),
                                VaadinSpringDataHelpers.toSpringDataSort(query))
                ).stream(),
                query -> memberService.countByFilter(memberFilterModel).intValue());
    }
``` 

Hope it will be helpful for somebody
