### ISSUE TITLE
Provide a way to style a content wrapper for the dialog.

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow-components#1366]
If you create a dialog using Java code then the content overlay will contain extra `div` inside `flow-component-renderer`.
This `div` is the container element which is added as a virtual child to the `Dialog` element in its CTOR :
```
container = new Element("div");
getElement().appendVirtualChild(container);
```
when dialog is shown this div becomes a child of the `flow-component-renderer`  element and it wraps the dialog content.
Since this element is internal for  `Dialog` implementation its not possible to access to it anyhow and it's not possible to influence on this element. So you can't style it easily.

It's not clear which API should be used to make it work. We definitely don't want to open this container element as is for developers. So we need provide API which allows somehow to do some restricted number of actions.

See details in vaadin/vaadin-dialog-flow#69.

**Comment by web-padawan** [comment]
The usage of `flow-component-renderer` and related `div` wrapper were removed in V24, see https://github.com/vaadin/flow-components/pull/4483 and https://github.com/vaadin/flow-components/pull/4499. 
While the issue is still valid for earlier versions, I don't think we'd add any API for them at this point. Closing.
