### ISSUE TITLE
Feature: Removing HeaderRow from the Grid

### ISSUE THREAD

**Issue by anasmi** [vaadin/flow-components#1538]
There is a feature of adding a HeaderRow to the Grid, but there seems not to be any server-side API for removing one. 

It would be nice if this feature would be also available. 

Thanks!

**Comment by MingjieZhu** [comment]
We need the feature too. Our app needs to toggle show/hide column filter header. right now, after turn it on, there is no way to remove it.

**Comment by voodoohoo** [comment]
Same here. Need to show/hide customizable sums as footer rows. Any news are greatly appreciated

**Comment by komitoff** [comment]
Hey I read what is written here. I wanted to ask about footers. In vaadin8 were possible to dynamically add and remove footers to a grid (and add a footer at given position), but in vaadin flow seems to not working. 

One more thing - is it somehow possible to add different style to different footer in the same grid, because from the FooterRow.class there is no possibility to add any html attributes. 
Thanks in advance

**Comment by pichlerm** [comment]
Please fix this, we also need this feature to hide a custom filter row (Vaadin 8: Grid.removeHeaderRow).

I tried the following workaround to remove a custom header row, but when removing the last header row (internally stored at index 0) I get the IllegalArgumentException from removeColumnLayer.

```
package com.vaadin.flow.component.grid;

import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

public class PatchedGrid<T> extends Grid<T> {

  private static final long serialVersionUID = -1923643109637196955L;

  /** @see #getHeaderRows() */
  public void removeHeaderRow(int i) {
    List<ColumnLayer> headerLayers = getColumnLayers().stream()
      .filter(ColumnLayer::isHeaderRow)
      .collect(Collectors.toList());
    Collections.reverse(headerLayers);
    ColumnLayer layer = headerLayers.get(i);
    removeColumnLayer(layer);
  }
}
```

**Comment by hoshie82** [comment]
It's possible to hide the row with css:
```
:host([hide-header-row]) {
    thead :nth-child(1)[part='row'], thead :nth-child(2)[part='row'] {
        display: none;
    }
}
```
Now you can set 
```
    void setHeaderRowVisible(boolean visible) {
        grid.getElement().setAttribute("hide-header-row", !visible);
    }
```
dynamically to hide the row... 
Could cause problems with resizing columns... and is more shine than a solution.. But maybe it could help for smaller projects..


But _yes_ ... I'd like to have a server side solution, too ^^

**Comment by silvan-lincan** [comment]
Thank you @hoshie82 

Looks like this still works for Vaadin 23.2, but I am using it with Theme Variants (just a preference).
Example for dynamically hiding second header, used as filter, (since the first one is with column headers and has to stay):

```
:host([theme~="hide-filter-header-row"]) thead :nth-child(2)[part="row"] {
	display: none;
}

..... depending on the conditions .......
grid.addThemeName("hide-filter-header-row");
.....
grid.removeThemeName("hide-filter-header-row");
```

**Comment by stefanuebe** [comment]
+1 on this issue to be fixed to allow real removement of header and footer rows

**Comment by fleahy** [comment]
Another +1. A secondary header row (for filtering, for example), has a massive performance penalty when there are a large number of columns as reported in #4565. A temporary work around is to allow the user to toggle the filtering header row but once it is created there's no way to toggle its visibility or even remove it. It seems like this should be a pretty standard feature of the grid.

**Comment by TorstenBMR** [comment]
another +1 from me

**Comment by web-padawan** [comment]
Thank you all but please refrain from comments like +1 and instead just upvote the issue.

Just to clarify, the concept of header and footer rows in Grid is overly complicated by design as it's based on the column groups API in the web component. This imposes certain limitations e.g. related to freezing columns.

I would recommend to avoid using overly complex UIs unless absolutely necessary, and follow the principle "do less".
Especially when it comes to heavy data grids, this might affect UX and cause a notable performance impact.

While I also understand that this feature is highly requested, let me emphasize that it's currently not planned.

**Comment by fleahy** [comment]
In my use-case the grid needs a header row at the top with column names and a filter header row beneath that one so users can select what to filter. This is a very common pattern that I wouldn't call overly complex. 
The reason for needing to be able to add/remove the filter row at all is because for grids with more than 10 or 20 columns, the initial append of the second header row makes it very slow, many seconds regardless of number of data rows. 

It seems that the design based on column groups is not the best approach - if I understand it correctly the column groups are not used for the first header row, only for second onwards. Should a different design be implemented instead to avoid this and other issues (eg #1054 )?

**Comment by rolfsmeds** [comment]
The way headers are modelled in the Grid component would almost certainly benefit from a refactorization. Unfortunately that's not a simple and quick task.

The default header row has some special properties that makes it difficult to remove, so I think the most realistic plan is to make it possible to remove additional header and footer rows, with a solution that somehow takes into account grouped columns (e.g. by throwing an exception if you try to remove a header row with groupings). @tomivirkki does that sound reasonable to you?

Btw @fleahy there are some performance improvements, including a lazy column rendering feature, coming to Grid in 24.1, so that might already solve your performance issue.

**Comment by fleahy** [comment]
@rolfsmeds, very excited to hear about performance improvements to the Grid, we make extensive use of it and that will be of great benefit to us. We're currently on 23 but have plans in place to get to 24, eager to test those changes when they come up!

**Comment by stefanuebe** [comment]
Here is a workaround for V24 using the internal api plus some client side styling to remove header / footer rows. It utilizes Reflection since most of the additional classes are package-private. If you use it and find any issues, please contact me. Also as always with such solutions, it might be, that it breaks with future releases. 

```java
public static class CustomGrid<T> extends Grid<T> {
        private boolean headerVisible = true;
        private boolean footerVisible = true;

        public CustomGrid(Class<T> beanType) {
            super(beanType);
        }

        @Override
        public FooterRow appendFooterRow() {
            setFooterVisible(true);
            return super.appendFooterRow();
        }

        @Override
        public HeaderRow appendHeaderRow() {
            setHeaderVisible(true);
            return super.appendHeaderRow();
        }

        @Override
        public FooterRow prependFooterRow() {
            setFooterVisible(true);
            return super.prependFooterRow();
        }

        @Override
        public HeaderRow prependHeaderRow() {
            setHeaderVisible(true);
            return super.prependHeaderRow();
        }

        public int removeFooterRows() throws Exception {
            setFooterVisible(false);
            return removePartRows(false);
        }

        public int removeHeaderRows() throws Exception {
            setHeaderVisible(false);
            return removePartRows(true);
        }

        /**
         * Removes all outer layer rows of the given type and clears the most inner one, if any exists. Will
         * also hide the specific part on the client side using display: none.
         * <br><br>
         * Uses reflection due to package-protected access of some of the grid helper classes.
         * @param header remove rows of header (true) or footer (false)
         * @return amount of removed rows (includes the inner most, cleaned one)
         * @throws Exception if any reflection things go wrong
         */
        @SuppressWarnings({"rawtypes", "unchecked"})
        private int removePartRows(boolean header) throws Exception {
            String isPartRowMethod = header ? "isHeaderRow" : "isFooterRow";
            String asPartRowMethod = header ? "asHeaderRow" : "asFooterRow";
            String partRowField = header ? "headerRow" : "footerRow";

            int count = 0;

            List layers = getColumnLayers();
            Object mostInnerLayer = layers.get(0);
            ArrayList wrapped = new ArrayList(layers); // wrap to preven ConcurrentModExc
            for (Object layer : wrapped) {
                boolean isPartRow = (boolean) MethodUtils.invokeMethod(layer, true, isPartRowMethod);
                if (isPartRow) {
                    if (layer == mostInnerLayer) {
                        // special handling for the "most inner" layer as that must not be removed.
                        // instead we clear all the cells, remove the row from the layer to prevent zombies and then
                        // hide the part via css on the client.
                        // a check, if the ref exists at all is not necessary, that is done by isPartRow already
                        Object partRow = MethodUtils.invokeMethod(layer, true, asPartRowMethod);
                        List cells = (List) MethodUtils.invokeMethod(partRow, true, "getCells");
                        for (Object cell : cells) {
                            MethodUtils.invokeMethod(cell, true, "setText", "");
                        }
                        FieldUtils.writeField(layer, partRowField, null, true);

                    } else {
                        // any outer layer can simply be removed
                        MethodUtils.invokeMethod(this, true, "removeColumnLayer", layer);
                    }
                    count++;
                }
            }

            return count;
        }


        private void setHeaderVisible(boolean visible) {
            if (headerVisible != visible) {
                setPartVisible("tHead", visible);
                headerVisible = visible;
            }
        }

        private void setFooterVisible(boolean visible) {
            if (footerVisible != visible) {
                setPartVisible("tFoot", visible);
                footerVisible = visible;
            }
        }

        private void setPartVisible(String part, boolean visible) {
            // hide or show a part of the table (tHead or tFoot)
            getElement().executeJs("const element = this.$.table." + part + ";" +
                                   "if(element) {" +
                                   "    element.style.display = $0;" +
                                   "}", visible ? "" : "none");

        }
    }
```

**Comment by kgromov** [comment]
@stefanuebe Thanks for workaround.
But once removed newly appended rows (tried with footer) are not visible. 
Looking forward for server-side solution.

**Comment by ppawlowski15** [comment]
Not sure if that's what you mean but to hide first row (row showing column names) u just need to setHeader as null component for every column:

grid.getColumns().forEach(col -> col.setHeader((Component) null));
