### ISSUE TITLE
TreeGrid Item Clicklistener only fires for leaf nodes

### ISSUE THREAD

**Issue by aze-kool** [vaadin/flow-components#1684]
https://vaadin.com/forum/thread/17773630/treegrid-itemclicklistener-not-working-properly

SelectionListner/ItemClicklistner are only called for leaf nodes and root nodes. for nodes having child nodes, the event is not fired. This is quite problematic for migration project. Since the tree component is not there and the only choice is the TreeGrid.

**Comment by mvysny** [comment]
Building on @tomivirkki 's workaround, taking advantage of Vaadin Themes which allow for easy component customization as documented here: https://vaadin.com/docs/v14/flow/styling/custom-theme

Create a file named `frontend/themes/yourtheme/components/vaadin-grid-tree-toggle.css` with the following contents:
```css
:host {
    pointer-events: none;
}

[part="toggle"] {
    pointer-events: auto;
}
```
It will be picked up automatically by Vaadin Theme engine and applied to the `<vaadin-grid-tree-toggle>` component.

**Comment by web-padawan** [comment]
Closing in favor of #1091 which is essentially the same.

**Comment by chkpnt** [comment]
> Hi, @erwandrezen The easiest way would be to create a css file (`/frontend/styles/grid-tree-toggle-adjust.css`) with:
> 
> ```css
> :host {
>   pointer-events: none;
> }
> 
> [part="toggle"] {
>   pointer-events: auto;
> }
> ```
> 
> and then use the [new `CssImport` annotation](https://vaadin.com/docs/v14/flow/importing-dependencies/tutorial-include-css.html#using-cssimport) with something like `@CssImport(value="./styles/grid-tree-toggle-adjust.css", themeFor="vaadin-grid-tree-toggle")`

This worked fine for me with Vaadin 14. But with Vaadin 23, the custom CSS doesn't seem to be applied to `vaadin-grid-tree-toggle`. I can still see `vaadin-grid-tree-toggle` in the DOM, and if I add the css manually via the browser's developer tools, the fix is working, but somehow the mixin doensn't seem to be bundled while building the app. But other `@CssImport`-statements still works, so am I missing a change within the Grid component? (I've already read the [upgrade instructions](https://vaadin.com/docs/latest/upgrading/?from=14&to=23&isFlow=true&isFusion=false&isSpring=true&isTypeScript=false&isCustomStyling=true&isInstructionsDisplayed=true))
