### ISSUE TITLE
TreeGrid recalculateColumnWidths doesn't recalculate on first attempt

### ISSUE THREAD

**Issue by roastedcpu** [vaadin/flow-components#1855]
## Description
After expanding a node on the client-side and executing `recalculateColumnWidths`, the hierarchy column width does not change / does not respect the newly loaded child nodes. Closing and opening the node again makes it work.

## Live Demo
![recalulateColumnWidth](https://user-images.githubusercontent.com/66945385/123949085-124a9200-d99a-11eb-9e9a-0f46e514378e.gif)

## Steps to reproduce
- add a tree grid, where one of the child nodes has a much longer text to be displayed in the column
- add an event listener for expanding nodes (`addExpandListener`) 
- in the listener call `recalculateColumnWidths`
- open in browser expand the root node

## Expected outcome
- hierarchy column width is increased and the text of the expanded child nodes is fully visible

## Actual outcome
- hierarchy column width is unchanged, text of the expanded child nodes is cut off

## Minimal reproducible example
```java
@Route("grid1864")
public class Grid1864 extends Div {
    public Grid1864() {
        final TreeNode root = new TreeNode("root", null);
        final TreeNode layer1 = new TreeNode("layer1 LONG STRING", root);
        final TreeNode layer2 = new TreeNode("layer2 EVEN LONGER STRING",
                layer1);
        final TreeGrid<TreeNode> grid = new TreeGrid<>();
        grid.setWidth("300px");
        grid.setItems(Collections.singletonList(root), TreeNode::getChildren);
        grid.addHierarchyColumn(TreeNode::getName).setAutoWidth(true)
                .setHeader("Hierarchy");
        grid.addColumn(TreeNode::getName).setAutoWidth(true).setHeader("Name");
        grid.addExpandListener(
                treeNodeTreeGridExpandEvent -> grid.recalculateColumnWidths());
        grid.addCollapseListener(treeNodeTreeGridCollapseEvent -> grid
                .recalculateColumnWidths());
        add(grid);
    }

    public static class TreeNode {
        private final String name;
        private final TreeNode parent;
        private final List<TreeNode> children = new ArrayList<>();

        public TreeNode(String name, TreeNode parent) {
            this.name = name;
            this.parent = parent;
            if (this.parent != null) {
                this.parent.addChildren(this);
            }
        }

        public void addChildren(TreeNode... nodes) {
            this.children.addAll(Arrays.asList(nodes));
        }

        public String getName() {
            return name;
        }

        public TreeNode getParent() {
            return parent;
        }

        public List<TreeNode> getChildren() {
            return children;
        }
    }
}
```

**Comment by sissbruecker** [comment]
I updated the OP with more information.

Some more context from an internal discussion:

It's very likely that this issue has a different root cause than the one that was linked. The original issue was about using `recalculateColumnWidths` after making changes to the grids' data provider. The related PR fixed a synchronization issue in the Flow component, where on the client-side `recalculateColumnWidths` would be executed before updating the data provider in the grid.

This issue is about expanding a tree node and then calling `recalculateColumnWidths`, expecting the hierarchy to change its size based on the newly loaded child nodes. It seems likely that the issue here has to do with lazy loading, where the tree grid first needs to load the child nodes and then re-render, before `recalculateColumnWidths` could have an effect. It seems the setup from the example, where `recalculateColumnWidths` is called from the node expand event listener, will call `recalculateColumnWidths` before the child nodes have been loaded / rendered. This is also indicated by the fact that it works when trying it for a second time, as in that case the child nodes are already cached.
