### ISSUE TITLE
SplitLayout position - set manually + programatically - regression ?

### ISSUE THREAD

**Issue by roastedcpu** [vaadin/flow-components#2124]
### Description

In v21 if one sets the splitter position programatically and then slides it manually, it can't be re-set again to the same value.
This behaves as expected in v20.

### Expected outcome

By manually sliding the splitter and then clicking 'set to 0', the slider should go back to the position 0.

### Actual outcome

The splitter position doesn't change

### Minimal reproducible example

```java
SplitLayout splitLayout = new SplitLayout();
splitLayout.addToPrimary(new Div(new Span("PRIMARY")));
splitLayout.addToSecondary(new Div(new Span("SECONDARY")));
add(splitLayout);

splitLayout.addToSecondary(new Button("SET TO 0", buttonClickEvent -> splitLayout.setSplitterPosition(0)));
splitLayout.addToSecondary(new Button("SET TO 90", buttonClickEvent -> splitLayout.setSplitterPosition(90)));

splitLayout.setSplitterPosition(0);
```

### Steps to reproduce

1. Manually slide the splitter to a random position
2. Click 'set to 0'

Or:

1. Click 'set to 90'
2. Manually slide the splitter to a random position
3. Click 'set to 90'

**Comment by sissbruecker** [comment]
The issue here is that the Flow component does not get notified about the fact that the `flex` style value has changed on the client, which causes the Flow component to not update the style, because it thinks the value is still the same.

Flow of events:
- set position to 0 on server: Flow component updates `flex` style to `flex: 1 1 0.0%`
- user changes position manually on client, which changes the `flex` style to a different value, the Flow component does not receive this update
- set position to 0 on server: Flow component updates `flex` style to `flex: 1 1 0.0%` - which for the Flow component is the same value as before, so the client-side element will not be updated
