### ISSUE TITLE
[button] Double clicking button should not fire ClickEvent by default

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow-components#2173]
In many apps it is desirable that double clicks are filtered.

This is basically easy to do in Vaadin as follows

```
    button.addClickListener(event -> {
        if (event.getClickCount() == 1) {
            // Do something
        }
    });
```

However this is verbose if needed for all buttons etc.

One can ofcourse extend button to avoid boiler plate.

If this is the prevalent use case, it is a bit bad DX and it would be more preferable if button click is not fired on multiple clicks by default and you  need to explictly enable multi click feature

Say

`button.allowMultipleClicks(true);`

**Comment by guame** [comment]
Is it possible to add an option to disable click until completion of the click action ?

**Comment by TatuLund** [comment]
> Is it possible to add an option to disable click until completion of the click action ?

I am not sure what you mean by this question, but the following method do exists. It will disable the button after first click. However the use case of the enhancement request is not related to this. 

`button.setDisableOnClick(true);`

**Comment by guame** [comment]
Ideally the button should be able, if asked, to disable itself until the completion of the listener call.

In fact it is related since this ticket has been after a request of one of my team mate. 
In our case the double/triple/multiple clicks issue triggered call to a REST service, which in turn started an heavy process on another server multiple time. 

So the idea would to not only prevent a 'double click' but also to prevent any click while the event is still being processed.

We can do a specialized version of the Vaadin button and implement this feature ourselves, like we just did to prevent the double click, but it might be useful for other users to have this kind of behavior available out of the Vaadin box.

**Comment by TatuLund** [comment]
More complete workaround example in here: https://gist.github.com/TatuLund/8232836857275292a26b4dfe84cc9c38
