### ISSUE TITLE
GridPro: grid.select call within cell focus listener stops click event

### ISSUE THREAD

**Issue by drewharvey** [vaadin/flow-components#2266]
### Description

In the example below, you expect clicking the button to show a notification.  Normally this works.  However, the cell focus listener causes the button click to not fire on the user's first click.

```
GridPro<String> grid = new GridPro<>();

grid.setEditOnClick(true);

grid.addColumn(new ComponentRenderer<>(() -> {
    return new Button("Open", e -> {
        Notification.show("test");
    });
}));

// this use of grid.select(...) is causing the issue
grid.addCellFocusListener(e -> {
    if (e.getItem().isPresent()) {
        grid.select(e.getItem().get());
    }
});

grid.setItems("doesn't matter");

add(grid);
```

### Environment

Vaadin 22 alpha 8

Tested in Chrome

**Comment by sissbruecker** [comment]
The `Grid.select` call triggers a refresh for the selected item in the data communicator. That in turn causes the component renderer to update. As the component renderer in the snippet does not implement an update function, the component renderer will recreate the button, instead of updating the existing one:
https://github.com/vaadin/flow-components/blob/3c7398274376d498eb5181b210c7d7c86a1e3bb7/vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java#L260-L264

That means the existing button instance that was clicked, and its event listener will be discarded. I have not debugged that far, but I assume that also causes the pending click event not being handled. I'm not sure if we can expect from Flow to handle the pending events before the button is discarded or not. The component renderer's upate method is called from Flow's `AbstractComponentDataGenerator`, which means this might be a Flow issue.

However this can be easily fixed from the application side by implementing an update function for the component renderer:
```java
        grid.addColumn(new ComponentRenderer<>(item -> new Button("Open", e -> {
            Notification.show("test");
        }), (component, item) -> component));
```
With that the button is not recreated every time a selection happens, and the click event is processed.

**Comment by sissbruecker** [comment]
After another look and a discussion in the team our stance is that this is expected behavior, even though I can see how it's a bit opaque how this combination of features leads to this outcome. To reiterate from above:
- Selecting an item in the grid causes the item to be refreshed and re-rendered. Refreshing the item does not seem necessary for the grid to function properly, but it's a reasonable assumption that custom renderers make use of the selection state, so removing the refresh is not an option at this point.
- The re-render triggered by the selection causes component renderers to recreate components if the they don't implement an update function. This is a reasonable default and lot's of applications probably rely on this behavior, also it makes them easy to use. Still, I'd say the unexpected part is probably here, and the API could be more explicit so that you have to opt-in into this behavior.
- Due to the component renderer recreating the components and their listeners, pending events for the previous component instances get discarded. This is expected, as the components which would have received the events are not part of the UI anymore. In this specific case the select is triggered from a `focus` event, which is generally triggered, and thus processed, before `click` events.

The solution for this issue would be to properly implement an update function for the component renderer to prevent it from recreating the component instances on every select / render:
```java
grid.addColumn(new ComponentRenderer<>(item -> new Button("Open", e -> {
  Notification.show("test");
}), (component, item) -> component));
```
Implementing an update function for component renderers, even if they are no-ops like the one above, seems like a good practice in general to avoid unnecessary recreation of the same components.
