### ISSUE TITLE
Dialog: draggable does not work with LUMO_NO_PADDING variant

### ISSUE THREAD

**Issue by drewharvey** [vaadin/flow-components#2324]
### Description

You can't drag (reposition) a dialog if you use `DialogVariant.LUMO_NO_PADDING`.

### Version & Browser

Vaadin 22 beta 1
Chrome latest

### Minimal reproducible example

```
Dialog d = new Dialog();
d.setDraggable(true);
d.addThemeVariants(DialogVariant.LUMO_NO_PADDING);
d.add(new VerticalLayout(new H2("Test")));
d.open();
```

**Comment by drewharvey** [comment]
I want a sticky dialog header (title, expand, close buttons) but it looks bad with padding.  But if you set padding to 0, the dragging doesn't work.  Here is an example of the dialog with padding (doesn't look right):

![header-with-padding](https://user-images.githubusercontent.com/2496955/141028443-84602337-f59a-4166-9457-6da2d96f5bca.jpg)

**Comment by DiegoCardoso** [comment]
That's expected, since the by default Dialog only uses its `content` part as a drag handler, but to avoid unwanted behavior, we prevent dragging from any children of `content`.

However, you can set your own draggable areas within the Dialog by adding a `draggable` class to the element, as can be seen on the [Draggable docs](https://vaadin.com/docs/latest/ds/components/dialog/#draggable):

> Any component contained within a Dialog can be marked and used as a drag handle by applying the draggable class name to it. You can choose whether or not to make the component’s content draggable as well, or just the component itself.

**Comment by drewharvey** [comment]
Aw yes, you're correct.  I did not read enough into the docs!  Thank you for clarify - closing.
