### ISSUE TITLE
Exception in console when using a button created with TemplateRenderer in Grid

### ISSUE THREAD

**Issue by tulioag** [vaadin/flow-components#2355]
### Description
When clicking a button created with TemplateRenderer, an exception is thrown.

```
Uncaught TypeError: Cannot read properties of null (reading '__data')
    at HTMLElement.$0.handleClick (eval at jt (FlowClient.js?2d7e:1), <anonymous>:3:152)
    at HTMLElement.handler (template-stamp.js?382f:91)
$0.handleClick @ VM6571:3
handler @ template-stamp.js?382f:91
```

![Selection_013](https://user-images.githubusercontent.com/28783969/142203519-b7fee817-130e-4d80-9974-4268cabb8ab0.png)

### Minimal reproducible example

```java

import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.data.renderer.TemplateRenderer;
import com.vaadin.flow.router.Route;

@Route(value = "")
public class GridView extends HorizontalLayout {

    public GridView() {
        Grid<String> grid = new Grid<>();
        grid.setItems("1","2","3");
        grid.addColumn(s -> s);
        grid.addColumn(createEditButtonRenderer());
        add(grid);
    }

    private TemplateRenderer<String> createEditButtonRenderer() {
        String template =
            "<vaadin-button theme=\"icon tertiary\" on-click=\"handleClick\" >"
                + "<vaadin-icon icon=\"vaadin:edit\" slot=\"prefix\"></vaadin-icon>"
                + "</vaadin-button>";
        return TemplateRenderer.<String>of(template)
            .withEventHandler("handleClick", this::showNotification);
    }

    private void showNotification(String string) {
       Notification.show(string);
    }
}

```

### Steps to reproduce

1. Create a project in https://start.vaadin.com/app/ using Vaadin 22.0.0.beta3
2. Add the view above to the project
3. Go to localhost:8080
4. Click in any of the buttons
5. Check that the error is shown in the console.

### Tested with
- Vaadin 22.0.0.beta3
- Chrome
- Linux

**Comment by tomivirkki** [comment]
Fix in https://github.com/vaadin/web-components/pull/3078

As a workaround, you can add a dummy listener to the inner elements, to `<vaadin-icon>` in this case: `on-foobar=\"foobar\"`. This works because it makes Polymer add a `_dataHost` reference to the inner element, which in turn is being accessed as a [fallback mechanism in the RendererUtil](https://github.com/vaadin/flow-components/blob/e68fd61a0866957a4cc6ea6f09ae2783a3864e87/vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/RendererUtil.java#L126)
