### ISSUE TITLE
DatePicker triggers `value-changed` when attached

### ISSUE THREAD

**Issue by probert94** [vaadin/flow-components#2691]
### Description

In an application I am working on, I use `UI#push` to force an update of the client site state (in my case I want to show a loading indicator). Now I noticed, that the value of displayed `DatePicker` is wrongly set to `null`.
I found that this is caused by a `ValueChangeEvent` coming from the client.
After some debugging, I found that a `value-changed` event is triggered during the `ready` of the webcomponent, because the value changed from `undefined` to `""`.
If the value on the server is still the same at this time, no `ValueChangeEvent` will be triggered but if the value on the server changed in the mean time, a `ValueChangeEvent` with `fromClient=true` is triggered and the server side value is changed to `null`.
This can even result in a difference between the client side value and the server side value.

The `value-changed` event on the client also happens for `TextField` (and probably other fields as well) but the server side `ValueChangeEvent` only seems to happen with `DatePicker`.

### Expected outcome

There should be no `ValueChangeEvent` with `fromClient=true` unless the user manually changed the value on the client side.

### Actual outcome

There is an initial `value-changed` event on the client, which might create a `ValueChangeEvent` on the server, if the server value changed in the mean time.

### Live Demo (optional)

Notification that shows, when the server receives a `ValueCHangeEvent` from client:
![image](https://user-images.githubusercontent.com/18258317/154485610-2975660e-39b2-4a3e-9881-41d51a14ecf5.png)
It triggers immediately after opening the page, basically as soon as the `Datepicker` is attached.

Pressing the `Show values` button shows the server side values:
![image](https://user-images.githubusercontent.com/18258317/154485790-c66d8c5d-6950-4830-a5ba-b91ce0a7880f.png)
The date on the server is now `null`, while the client shows the expected value (the current date).

### Minimal reproducible example
```
  private DatePicker dp;
  private TextField tf;

  public EmptyView() {
      dp = new DatePicker();
      dp.addValueChangeListener(e -> {
          if (e.isFromClient())
              Notification.show("Date change from client: " + e.getValue());
      });
      tf = new TextField();
      tf.addValueChangeListener(e -> {
          if (e.isFromClient())
              Notification.show("Text change from client: " + e.getValue());
      });
      Button btn = new Button("Show values", e -> {
         Notification.show("Date: " + dp.getValue());
         Notification.show("Text: " + tf.getValue());
      });
      add(dp, tf, btn);
  }

  @Override
  protected void onAttach(AttachEvent attachEvent) {
      super.onAttach(attachEvent);
      attachEvent.getUI().push();
      dp.setValue(LocalDate.now());
      tf.setValue("Hello world");
  }
```

### Steps to reproduce

1. Download a Vaadin 22 starter with only an `EmptyView`
2. Enable `Push` in the `Application`
3. Copy the above code into the `EmptyView`
4. Run the project and open the page, it will show a notification that the date has changed
5. Press the `Show values` button and it will show a notification with the current server side values.

### Environment

- Vaadin 22.0.5
- Windows 10 x64

**Comment by yuriy-fix** [comment]
Could be related: https://github.com/vaadin/flow-components/issues/1360

**Comment by vursen** [comment]
Confirmed that the issue is actually reproducible for both DatePicker and TimePicker, and I guess for DateTimePicker as well, but I didn't check that.

The described behavior comes out of the fact that DatePicker's default value is different on the client-side and the server-side. It is an empty string on the client-side and `null` on the server-side whereas TextField's default value is an empty string on both and that is why it is not affected.

### What happens in the example in detail: 

1. **Server:** Adds DatePicker with no value
2. **Server:** Pushes
3. **Client:** Initializes the DatePicker web component with the value `null`
4. **Client:** Polymer fires `value-changed` with `null` => `""` because this is the default value from the web component's point of view.
5. **Client:** In response to that, Flow Client schedules a round-trip request to sync the value on the server-side.
6. **Server:** Sets DatePicker value to `01.01.2022` and releases the initial HTTP request
7. **Client:** Sets the DatePicker web component value to `01.01.2022`
8. **Server:** Starts processing the scheduled round-trip request with the updated value.
9. **Server:** Updates DatePicker value to `null` because it cannot parse the empty string into a date.

### Possible solution

One way could be to change the web component's default value to `null`.

**Comment by sissbruecker** [comment]
Did a quick test and can verify that initializing the Flow component's `value` property with an empty string fixes the issue. Setting it to an empty string makes the Flow component discard the initial `value-changed` event that the web component dispatches, because then the event value and the property value are equal.

I remember a similar change for the Select Flow component, where we needed to make sure that the Flow components `value` property is aligned with the default value of the web component: https://github.com/vaadin/flow-components/pull/973/files#diff-1c027c9076652ce3a2c641ac7407c10cc3a87846a37ee152c27aa9fe59aad609R126-R129. So this is probably a reasonably approach.

Apart from that I'm a bit confused why you would call push during `onAttach`, which seems to be causing the value desync. That seems like asking for trouble. But maybe that's just a simplified reproduction of a separate thread pushing while the UI thread attaches.

As a side note, I think it's kind of problematic that we rely on the `value-changed` Polymer event, which always triggers when the web component initalizes. If we could use a custom event that would only be dispatched when the user actually changed something, that would make the value synchronization easier.

**Comment by probert94** [comment]
> I'm a bit confused why you would call push during onAttach , which seems to be causing the value desync. That seems like asking for trouble.

It's indeed only simple way to reproduce the issue.

**Comment by sissbruecker** [comment]
> It's indeed only simple way to reproduce the issue.

Cool, thanks for confirming.

**Comment by vursen** [comment]
The issue has been fixed. Stay tuned for V22.0.9 which will be out soon.
