### ISSUE TITLE
ComboBox doesn't fetch the next page

### ISSUE THREAD

**Issue by roastedcpu** [vaadin/flow-components#2736]
### Description

For certain ComboBox pageSize values only the first page is fetched

### Expected outcome

After scrolling to the bottom the next page should be fetched and all items should  end up being displayed at some point.

### Actual outcome

Only the first X items are shown, according to the pageSize. But it only happens for specific pageSize values

### Minimal reproducible example

```
// Bug doesn't happen:

ComboBox<String> comboBox = new ComboBox<>();
﻿add(comboBox);
﻿
﻿List<String> items = new ArrayList<>();﻿
﻿for(int i=0; i<53; i++) {
    ﻿items.add("Item #" + i);
﻿}
﻿
﻿comboBox.setDataProvider(new ListDataProvider<>(items));
﻿comboBox.setPageSize(20);


// Bug happens:

ComboBox<String> comboBox = new ComboBox<>();
﻿add(comboBox);
﻿
﻿List<String> items = new ArrayList<>();﻿
﻿for(int i=0; i<50; i++) {
    ﻿items.add("Item #" + i);
﻿}
﻿
﻿comboBox.setDataProvider(new ListDataProvider<>(items));
﻿comboBox.setPageSize(20);
```

### Environment

- Vaadin version: v14.8.4 / v22.0.6

**Comment by sissbruecker** [comment]
Can confirm the issue. I could not reproduce it with the web component. After some investigation I think the issue is in the connector, especially part:

https://github.com/vaadin/flow-components/blob/master/vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js#L331-L345
```js
// Perform filter on client side (here) using the items from specified page
// and submitting the filtered items to specified callback.
// The filter used is the one from combobox, not the lastFilter stored since
// that may not reflect user's input.
const performClientSideFilter = tryCatchWrapper(function (page, callback) {

    let filteredItems = page;

    if (comboBox.filter) {
        filteredItems = page.filter(item =>
            comboBox.$connector.filter(item, comboBox.filter));
    }

    callback(filteredItems, filteredItems.length); // <-- passes max. the size of the page to the 
                                                   // data provider callback
});
```
When not using a server-side filter, then every page received by the connector is run through the function above. In the last line the data provider callback is called, passing the items of the page and the total item count to the web component. However for the total count it passes the number of filtered items from that page, rather than the actual total amount of items. 

A quick test with removing the call to `performClientSideFilter` seems to solve the issue, so a fix would likely need to be applied there.

**Comment by KiteDX** [comment]
As this was also reported for "Vaadin version: v14.8.4", will this also be part of one of the upcoming Vaadin 14 releases?

**Comment by sissbruecker** [comment]
@KiteDX It is now back-ported it to v14.8: https://github.com/vaadin/flow-components/pull/2773

**Comment by KiteDX** [comment]
> @KiteDX It is now back-ported it to v14.8: #2773

That is great news! Thank you for the info
