### ISSUE TITLE
[combo-box] Dropdown opens at the bottom even if there is not enough space

### ISSUE THREAD

**Issue by finaris-cs** [vaadin/flow-components#2820]
### Description

I have a ComboBox located near bottom of the page. When i open it, the drop down list appears below (where there is nearly no space), instead of above.

![image](https://user-images.githubusercontent.com/19190710/157071782-faf07b54-0fe4-4469-ab86-6fa9f126e11e.png)

### Expected outcome

Drop down list appear should appead above, if below is only little space.
An API to Combo allowing to set the desired position (ABOVE | BELOW) would also be helpful if the automatic detection cannot be made working in all cases.

### Actual outcome

Drop down list appears below, user can only see 1 item and hardly scroll to the others.

### Environment

- v22.0.7
- Windows 10

### Browsers Affected

- [x ] Chrome
- [ x] Firefox
- [x ] Edge

**Comment by yuriy-fix** [comment]
@finaris-cs, could you please provide a code snippet to reproduce the issue?

**Comment by tomivirkki** [comment]
@yuriy-fix the issue is also visible in our demos. The dropdown first opens downwards even though there's much more room above the field. Once you scroll (downwards), the alignment is fixed. Some miscalculation on initial open in [overlay-position-mixin](https://github.com/vaadin/web-components/blob/d643d95bfc9c905470e95272de812f446c0c38fd/packages/vaadin-overlay/src/vaadin-overlay-position-mixin.js#L196).

https://user-images.githubusercontent.com/1222264/157229347-14b6121f-a377-4dea-a32d-16ec4cba4016.mp4

**Comment by finaris-cs** [comment]
> @finaris-cs, could you please provide a code snippet to reproduce the issue?

the vaadin demos link by [tomivirkki](https://github.com/tomivirkki) should be sufficient, right?
If not let me know

**Comment by web-padawan** [comment]
Seems like in case of combo-box, this [logic](https://github.com/vaadin/web-components/blob/d643d95bfc9c905470e95272de812f446c0c38fd/packages/vaadin-overlay/src/vaadin-overlay-position-mixin.js#L225-L226) needs to be modified to not rely on content height (it's causing this issue).
The problem is that `spaceForDefaultAlignment > contentSize` is always true when opened at the bottom of the screen.

So we might want to disable this specific check for combo-box to only check for available space.

**Comment by tomivirkki** [comment]
Would it work if the combo-box overlay was assigned a min-height?

**Comment by web-padawan** [comment]
Here is how it works in the [Vaadin 14 version](https://github.com/vaadin/vaadin-combo-box/blob/01f1165efdcdb2ddc2c41809561c126e016f4f61/src/vaadin-combo-box-dropdown.html#L262-L270). 

Regarding `min-height`, I guess we could add custom CSS property to control it.

**Comment by HermanBovens** [comment]
This is currently blocking our upgrade of an application from V14 to V22.
Is there a (programmatic) workaround?  I had opened issue https://stackoverflow.com/questions/71704585/vaadin-22-opened-combobox-does-not-position-correctly before I saw this ticket.

**Comment by sissbruecker** [comment]
A hacky workaround to force the combo box to open upwards:
```js
Object.defineProperty(comboBox.$.dropdown.$.overlay.$.overlay, "offsetHeight", {
  get() {
    // Minimum space below combo box to open downwards, use large number to always open upwards
    return 200;
  }
});
```
I could not make it work with applying a min-height to the overlay, that creates some noticable vertical offset between the input and the overlay.

**Comment by HermanBovens** [comment]
Note that for the `vaadin-select` component, this still works fine.  I'd assume the logic would be similar (or even shared) between both components?

**Comment by tomivirkki** [comment]
You can also workaround the issue by registering the following styles for `vaadin-combo-box-overlay`:
```css
[part~='overlay'] {
  min-height: 200px;
}
```

**Comment by novosadt** [comment]
Thank you [tomivirkki](https://github.com/tomivirkki) for the workaround. In my case for Vaadin 23.1, just used ```registerStyles(...)``` function in imported javascript styles module via ```@JsModule``` annotation in main java class:

```
registerStyles(
    'vaadin-combo-box-overlay',
    css`
    #overlay {
        min-height: 50px;
    }
  `,
);
```

**Comment by timb086** [comment]
The min height works, as long as there are many items and there would be a scrollbar anyway. When having only a couple of items and the dropdown opens with enough space to the bottom, it looks strange:
![image](https://user-images.githubusercontent.com/102505446/215957852-7f6f0cdc-2326-457a-82b2-cbf961e10431.png)

**Comment by tomivirkki** [comment]
The issue has been [fixed](https://github.com/vaadin/web-components/pull/5432) and backported to [23.3](https://github.com/vaadin/web-components/pull/5437) and [22.0](https://github.com/vaadin/web-components/pull/5438) branches. I'd expect the fix to be released with one of the upcoming patch releases (probably Vaadin 23.3.7 and 22.0.29)
