### ISSUE TITLE
[chart] svg-generator should not try to install nodejs if missing

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow-components#2837]
### Description

Currently the svg-generator tries to access the internet to download and install nodejs on a server. This can lead to huge red flags in a secured environment.

### Expected outcome

Please fail with an error message that nodejs is missing, instead of trying to download it.

The [docs](https://vaadin.com/docs/latest/ds/components/charts/svg-generator) even state that "Node.js must be installed for the generator to work."

### Actual outcome

Nodejs is tried to be installed on a secured server environment. if the server has internet access - node is even installed (in .vaadin).

### Minimal reproducible example

- export a chart on a system without nodejs

### Environment

- v22/23
- Any OS without nodejs

**Comment by sissbruecker** [comment]
Can confirm this. The SVG generator is using the Flow `FrontendTools` class to determine the location of the Node executable, however the purpose of that class is to provide a working frontend setup for developing Flow projects. As such the class will also download Node.js if it can not be found, or download a newer version if it deems the installed one too old. That last bit is quite bad, since that might trigger a download even if Node.js is installed on the production system.

**Comment by knoobie** [comment]
@sissbruecker Thanks for looking into this! Additionally I found this issue while trying to install a proper version: https://github.com/vaadin/docs/issues/1151 (luckily solved by now; but that would have been a real killer for this feature)

**Comment by sissbruecker** [comment]
Yeah, a somewhat recent change in Flow was that it requires the usage of Node 16. But that's really only for local development, and should not dictate the version that you need to have installed on a production system for the SVG generator. Unfortunately I can not give any recommendations for the specific version to use for the SVG generator, but at least recent major versions should work fine.

I'll try to open a PR for this soon.
