### ISSUE TITLE
Charts is not displaying no data label when series is empty

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow-components#3003]
Charts is not displaying no data label when series is empty when using Vaadin 23.0.4

See test code:

```
        Chart chart = new Chart(ChartType.LINE);
        Lang lang = new Lang();
        lang.setNoData("No data avaialble");
        ChartOptions.get().setLang(lang);
        Configuration config = new Configuration();
        List<Number> data = new ArrayList<>();
        ListSeries series = new ListSeries("Data",data);
        config.setSeries(series);
        chart.setConfiguration(config);
```

Result

![image](https://user-images.githubusercontent.com/14309836/162704032-9f4063aa-652f-408b-a22f-25180c3b2d40.png)

Would expect to see label "No data available"

**Comment by TatuLund** [comment]
The workaround is to set "empty-text" attribute directly.

`chart.getElement().setAttribute("empty-text", "No data");`

**Comment by sissbruecker** [comment]
It seems the web component implements its own `emptyText` property to control what message is displayed when no data is available. The logic for that property does not respect the global Highcharts setting currently, and will initialize each individual chart with a no data message of a single whitespace by default. 

It would be possible to change the logic to respect the global Highcharts setting. However that would also alter the behavior of the component, as now all charts that do not have a custom `emptyText` property set would start displaying the default Highcharts no data message. It is also not clear if the `emptyText` property was intentionally implemented so that the default Highcharts no data message would not show up.

An alternative would be to add an API for controlling the `emptyText` property to the Flow component. IMO that would make it easier to change the text, instead of using the global language option. But it would not solve the issue that setting the message globally is broken.

**Comment by alvarezguille** [comment]
I took a quick look, with space as the default value the `__emptyTextObserver` is always executed after the chart initialization overriding other configs at global or chart level.

> It would be possible to change the logic to respect the global Highcharts setting. However that would also alter the behavior of the component, as now all charts that do not have a custom emptyText property set

I think this is doable without the mentioned behavior change if we first set the global option to empty string/null/space (needs testing) instead of setting a space as default value for `emptyText`.

Additionally `lang` could be added to `Configuration` to allow per chart overrides of the global config, but that's a separate thing.

**Comment by sissbruecker** [comment]
> I think this is doable without the mentioned behavior change if we first set the global option to empty string/null/space (needs testing) instead of setting a space as default value for emptyText.

True, I was a bit worried about changing the global defaults, but if an empty no data message by default is expected that would actually make sense.
