### ISSUE TITLE
The AllFinishedEvent from the Upload component is not fired if there is only a single rejected file

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/flow-components#3088]
### Description

For example if you set the restrictions to only be pdf files and you try to upload a jpg file then the file will be correctly rejected and the `FileRejectedEvent `is fired. However no `AllFinishedEvent `event is ever fired. The `AllFinishedEvent `should be fired as it can be used to detect when the uploads are completed, whether successfully, rejected, or if they failed.

### Expected outcome

`AllFinishedEvent `is fired when all uploads are either completed or failed/rejected.

### Minimal reproducible example

See above.

### Steps to reproduce

See above.

### Environment

Vaadin version(s): Vaadin 23.0.6
OS: Windows

**Comment by tomivirkki** [comment]
> The AllFinishedEvent should be fired as it can be used to detect when the uploads are completed, whether successfully, rejected, or if they failed.

According to the [`AllFinishedEvent` documentation](https://github.com/vaadin/flow-components/blob/3b4d78ac222bf0418f038df43dd572bc46347e9a/vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/AllFinishedEvent.java#L21-L23): `"AllFinishedEvent is sent when the upload has processed all the files in its upload queue, regardless of whether all the receptions were successful or not."`

If a file gets rejected by the upload Web Component, nothing is really added to the upload queue, the file just gets ignored and the "file-reject" event is dispatched. So I'm thinking if making the `AllFinishedEvent` fire on "file-reject" (for a single file) would be unexpected for some users?

Tried this with a live example and made an `Upload` only accept png images with: `upload.setAcceptedFileTypes("image/png");`:

Dragging multiple png-files:
- `AllFinishedEvent` fires once all the files in the upload queue finish

https://user-images.githubusercontent.com/1222264/169007518-36d6b032-14ce-4730-967e-d4809277c50d.mp4

Dragging multiple png-files and a text file:
- `FileRejectedEvent` fires for the text file and it's not added to the upload queue
- `AllFinishedEvent` fires once all the files in the upload queue finish

https://user-images.githubusercontent.com/1222264/169007547-8c4144f1-d768-4b63-9d88-96b11a7a6695.mp4

Dragging a single text file:
- `FileRejectedEvent` fires for the text file and it's not added to the upload queue
- `AllFinishedEvent` does not fire since no uploads are attempted

https://user-images.githubusercontent.com/1222264/169007668-133b9cc2-f817-4f4a-9ffa-38d47a4156dc.mp4

**Comment by tomivirkki** [comment]
Closing as per the comments above. The feature works as expected.
Please let us know if you think there's still an issue.
