### ISSUE TITLE
CheckboxGroup :  calling setItemLabelGenerator(...) in a ValueChangeListener unchecks all checkboxes

### ISSUE THREAD

**Issue by SonReimer** [vaadin/flow-components#3131]
### Description

In a ValueChangeListener of a CheckboxGroup the label of the items are refreshed by calling setItemLabelGenerator(...).
When clicking on one of the checkboxes, the labels are changed, but the checkboxes are all unchecked afterwards.

### Expected outcome

I would expect, that the checked state of the checkboxes remain unchanged, exclusing the one clicked.

### Minimal reproducible example

[CheckboxGroupView.java2.txt](https://github.com/vaadin/flow-components/files/8632285/CheckboxGroupView.java2.txt)

### Steps to reproduce

Click one of the unchecked checkboxes

### Environment

Vaadin version(s):  23.0.6
OS: Windows 10

### Browsers

Chrome, Firefox

**Comment by tomivirkki** [comment]
Hi @SonReimer 
Verified the issue, although having the value cleared on setItemLabelGenerator [seems quite intentional](https://github.com/vaadin/flow-components/blob/3b4d78ac222bf0418f038df43dd572bc46347e9a/vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java#L469). Removing this behavior could be breaking change for someone.

You can work around the issue by making the itemLabelGenerator dynamic:

```java
group.setItemLabelGenerator(item -> {
    if (group.getValue().contains(item)) {
        return item.getCaption() + " (selected)";
    } else {
        return item.getCaption() + " (not selected)";
    }
});
// There doesn't seem to be a clean public API for having the refreshCheckboxItems called
group.addValueChangeListener(e -> group.setValue(group.getValue()));
```

Another option could be to use the new [setRenderer API](https://github.com/vaadin/flow-components/blob/3b4d78ac222bf0418f038df43dd572bc46347e9a/vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java#L602)
