### ISSUE TITLE
[spreadsheet] Raw use of  parameterized class 'Focusable' [1 day]

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/flow-components#3159]
Spreadsheet class implements `Focusable` but it doesn't pass any type as a parameter to the interface, which leads to this message:

<img width="649" alt="image" src="https://user-images.githubusercontent.com/262432/167805688-f609bdb5-5a98-41e5-8a6f-7521f78f2858.png">

This is likely because `Spreadsheet` for FW8 also implements `Focusable`, but this interface is not parameterized like in the Flow version.

However, checking a bit further, the APIs for both interfaces are a bit different. 

The FW8 version has:
```java
void focus();
int getTabIndex();
void setTabIndex(int tabIndex);
```

While the Flow version has:
```java
void focus();
int getTabIndex();
void setTabIndex(int tabIndex);
void blur();
ShortcutRegistration addFocusShortcut(Key key, KeyModifier... keyModifiers);
```

And it also extends `HasElement, BlurNotifier<T>, FocusNotifier<T>, HasEnabled`, which adds more API like listeners for focus and blur events.

Spreadsheet may not be able to support all of this functionality on its current state (eg. the SS client doesn't fire `focus` or `blur` events AFAIK), so we need to decide how to proceed with this interface.

**Comment by yuriy-fix** [comment]
Let's investigate why `Focusable` was implemented for the v8 version of Spreadsheet.

**Comment by tomivirkki** [comment]
Took a look into this. The `Focusable` interface was originally added to V8 Spreadheet [quite some time ago](https://github.com/vaadin/spreadsheet/commit/c1929fa1746562d4ff213e6f0c026a78534f62d1). There's not a lot of history available related to the change but according to the commit message it was done to prevent Spreadsheet from stealing focus on init.

In its current state, adding a new Spreadsheet on a page seems to result in having the focus automatically move to the first spreadsheet cell, regardless of whether the component implements `Focusable` or not.

https://user-images.githubusercontent.com/1222264/173058207-dfc7f910-57cc-4543-80bb-2a302b1428de.mp4

By default, the `<vaadin-spreadsheet>` host component is not focusable and never invokes focus/blur listeners attached to the component. If you use the `setTabIndex` API to make the host component focusable, the listeners work somewhat unpredictably: Focusing the host component invokes focus listeners. If focus moves from the host component to one of the internal focusable elements (like cells), blur listeners get invoked. If the focus moves back to the host, focus listeners get invoked again. Also, the styling of the host focus outline is not ok.

https://user-images.githubusercontent.com/1222264/173058766-50ace416-eec5-4ded-be86-9c7a0da2a258.mp4

I'd recommend removing the `Focusable` interface from Spreadsheet _for now_ since making the focus/blur listeners and `focus()` API work reliably may require some extra work on `<vaadin-spreadsheet>` (perhaps moving the spreadsheet internals inside a shadow root and have "blur" trigger on the host only when the focus completely leaves the Spreadsheet) and since it doesn't seem to deliver its original purpose of preventing the focus from getting "stolen" on init anyway.
