### ISSUE TITLE
FormLayout.addFormItem() without a label

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/flow-components#3170]
### Describe your motivation

In some cases such as when I want to add a TextField with a button on the end I will wrap it around a HorizontalLayout wrapper so that the Button is added at the end of the line. I can do this with a FormLayout by doing FormLayout.addFormItem(HorizontalLayoutWrapper, "text field label") which is ok but it removes the ability to setRequired on the field which is nice to have for the asterisk and so on. Therefore it would be great if it would be possible to addFormItem without a label as well and let the component within the HorizontalLayout wrapper manage the labels.

### Describe the solution you'd like

See description of motivation for solution

### Describe alternatives you've considered

See above

**Comment by web-padawan** [comment]
Thanks for the issue. Do I understand it correctly that you don't need the component's label to be placed on the left?
In that case, there is no point in using `addFormItem()` in my opinion as its purpose is mostly positioning the label.

You can add the `HorizontalLayout` into the `FormLayout` normally, using `add()` instead of `addFormItem()`

**Comment by yuriy-fix** [comment]
Closing as stale. Feel free to comment if still valid.
