### ISSUE TITLE
[spreadsheet] Importing spreadsheet files works unexpectedly

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow-components#3261]
Importing the test file `picture_sheet.xlsx` works unexpectedly. The outcome looks a bit different each time.

V8 Spreadsheet (expected):
![Screenshot 2022-06-01 at 16 04 49](https://user-images.githubusercontent.com/1222264/171411949-e63dc3d9-7420-493a-8010-b2d160dc5ba3.png)

V23 Spreadsheet:
![Screenshot 2022-06-01 at 16 05 50](https://user-images.githubusercontent.com/1222264/171411992-8eb73ed9-22bf-4afb-b439-0f13c790260d.png)

**Comment by tomivirkki** [comment]
The issue is caused by the following exception:
```
java.lang.NullPointerException: Cannot invoke "org.apache.xmlbeans.XmlAnySimpleType.getStringValue()" because "coordUnion" is null
        at org.apache.poi.ooxml.util.POIXMLUnits.parseLengthInner(POIXMLUnits.java:236)
        at org.apache.poi.ooxml.util.POIXMLUnits.parseLength(POIXMLUnits.java:167)
        at org.apache.poi.xssf.usermodel.XSSFClientAnchor.calcCell(XSSFClientAnchor.java:166)
        at org.apache.poi.xssf.usermodel.XSSFClientAnchor.getCell1(XSSFClientAnchor.java:202)
        at org.apache.poi.xssf.usermodel.XSSFClientAnchor.getCol1(XSSFClientAnchor.java:211)
        at com.vaadin.flow.component.spreadsheet.Spreadsheet.isOverlayVisible(Spreadsheet.java:4219)
        at com.vaadin.flow.component.spreadsheet.Spreadsheet.loadOrUpdateOverlays(Spreadsheet.java:4153)
        at com.vaadin.flow.component.spreadsheet.Spreadsheet.loadCells(Spreadsheet.java:3937)
```

Catching the exception makes the file import consistently each time.

**Comment by tomivirkki** [comment]
This turns out to be caused by a regression in Apache POI (starting from version 5.0.0)

The following snippet runs fine with POI version 4.1.2 but throws an exception with version 5.0.0 (and upwards):

```java
package com.mycompany.app;

import java.io.File;
import org.apache.poi.ss.usermodel.ClientAnchor;
import org.apache.poi.ss.usermodel.Drawing;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.poi.xssf.usermodel.XSSFDrawing;
import org.apache.poi.xssf.usermodel.XSSFShape;

public class App {
    public static void main( String[] args ) throws Exception {
        File file = new File("/path/to/picture_sheet.xlsx");
        Workbook workbook = WorkbookFactory.create(file);
        Sheet sheet = workbook.getSheetAt(0);
        Drawing<?> drawing = sheet.getDrawingPatriarch();
        for (XSSFShape shape : ((XSSFDrawing) drawing).getShapes()) {
            ClientAnchor anchor = (ClientAnchor) shape.getAnchor();
            System.out.println("Anchor col 1" + anchor.getCol1());
        }    
    }
}
```

One possible solution to this issue would be to downgrade POI version to 4.1.2

**Comment by WoozyG** [comment]
The NPE appears to come in due to changes from the OOXML update to schema version 5.  Previously absolutely positioned items implicitly were relative to (0,0), with no unit conversion, but now unit conversion is applied to everything.  That’s generally a good thing, but along with that, a method that used to return a primitive int/long now returns Object, so returns null instead of 0 in the absolute case.

It appears it worked before due to that primitive return.  The error here could be construed as correct, as absolutely positioned images, not tied to a cell, don’t have column and row references, and the “working” behavior before can be seen as an accident of default values.

This is specific to the XSSFClientAnchor implementation of the ClientAnchor interface.  HSSFClientAnchor is based on primitives in the constructor, while XSSFClientAnchor uses Object instances.

If Vaadin still needs to support old “*.XLS” files (HSSF format), then Vaadin will need to check the anchor type, and possibly cast to the concrete type.  Everything will be fine for HSSF files with embedded images, but for XSSF (*.XLSX) files like this test, the anchor needs to be cast to the subtype, and the position object used if needed.

AnchorType.DONT_MOVE_AND_RESIZE.equals(anchor.getAnchorType()) && anchor instanceof XSSFClientAnchor

In this case, the anchor doesn't have cell references at all, only a position object for absolute positioning relative to the worksheet origin.

When true, cast to XSSFClientAnchor, and use XSSFClientAnchor.getPosition() instead of cell references.  That may mean extra work implementing the overlay, though.  It may be possible to default to cell A1 in this case and call it good for now, if needed, I suppose, but I don't know how overlays are being done here in Flow.

**Comment by tomivirkki** [comment]
@WoozyG Thanks for looking into it! Just submitted a [PR](https://github.com/vaadin/flow-components/pull/3957) that fixes the issue. Added the check for the problematic image type and then anchored the image to cell A1 as you suggested. Always using A1 as the reference cell seems to have some drawbacks with Vaadin Spreadsheet but it's still a lot better than getting an exception thrown on import.
