### ISSUE TITLE
Focus behavior in view differs from focus behavior in Dialog

### ISSUE THREAD

**Issue by fabst2w** [vaadin/flow-components#3488]
### Description

When I press TAB key in a form that is in a view, then the content of the focused input field is selected.

When I press TAB key in a form that is dialog, then the content of the focused input field is NOT selected.

The behavior differs. Screenshots you can find here: https://stackoverflow.com/questions/72978063/vaadin-23-select-datepicker-content-at-onfocus-in-dialog

### Expected outcome

My expectation is that the focusing behavior is the same in dialogs as it is in views.

### Minimal reproducible example

Have a look here: https://stackoverflow.com/questions/72978063/vaadin-23-select-datepicker-content-at-onfocus-in-dialog

### Steps to reproduce

1. Use code from https://stackoverflow.com/questions/72978063/vaadin-23-select-datepicker-content-at-onfocus-in-dialog
2. Open view and press TAB key.
3. You will see that the focused input field's content is selected.
4. Press the button to open a dialog.
5. Press TAB key.
6. You will see that the focused input field's content is NOT selected.

### Environment

Vaadin version(s): 23
OS: Ubuntu 22.04

### Browsers

Chrome, Firefox

**Comment by simasch** [comment]
I have the same issue

**Comment by web-padawan** [comment]
Thanks for the issue. This is caused by the [focus trap logic](https://github.com/vaadin/web-components/blob/4fb709e15e78a2e1d12c7f38e5a28bfa7f028442/packages/component-base/src/focus-trap-controller.js#L104-L109) that prevents default behavior for <kbd>Tab</kbd> key and then calls `.focus()` on the correct element. We should add a check if an element is `<input>` or `<textarea>` and then call [`.select()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select).

**Comment by fabst2w** [comment]
Works fine. Thank you! :-)
