### ISSUE TITLE
Consider revising Upload button API

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/flow-components#3542]
### Describe your motivation

When I wanted to change the text of the `Upload` component button, these are the steps I took:

1. I was first looking for an API like `Upload.setText()` or `Upload.setCaption()`, only to discover that there is none.
2. I then noticed that there is `Upload.getUploadButton()`, but then I was surprised that `getUploadButton()` actually returns a `Component`, not a `Button`.
3. Next I tried casting the `Component` returned by `Upload.getUploadButton()`, only to discover that it returns null by default. Apparently, this is only intended to return the component set using `Upload.setUploadButton()` (the latter confusingly takes also a `Component` as an argument even though the setter name says "Button").
4. I then quickly skimmed through the `Upload` docs [page](https://vaadin.com/docs/latest/components/upload), but I couldn't quickly spot a title that indicates how I can change the button caption. 
5. FInally, upon googling, I found this oldish [forum thread](https://vaadin.com/forum/thread/14268922/vaadin-upload-change-upload-button-caption) which clued me that I should be using the i18n property to change the caption. This is available in the docs page examples but I missed it since I wasn't specifically looking to internationalize my Upload.

### Describe the solution you'd like

Here are some suggestions that would IMO improve DX:

- Offer an API like `Upload.setText()` or `Upload.setCaption()`. Using the i18n property is (a) not so obvious, and (b) an overkill if all I need is to change the button caption.
- Change the return type of `Upload.getUploadButton()` to `Button` and make it return the actual button used in the `Upload` component by default (not null).
- Create a new `Upload.setActionComponenet(Component c)` and `Upload.getActionComponenet()` to offer people the possibility to set a custom component to replace the default button.
- Update the docs' [Upload customization section](https://vaadin.com/docs/latest/components/upload/#customization) to mention explicitly how to change the upload button caption.

**Comment by web-padawan** [comment]
> Offer an API like Upload.setText() or Upload.setCaption()

We don't have `setCaption()` in any of the Flow components. Regarding `setText()`, using this method could potentially cause confusion because in `vaadin-upload` we have also a drop label ("Drop files here..." text element).

> Change the return type of Upload.getUploadButton() to Button and make it return the actual button

Note, the issue affects not only about `getUploadButton()` but also `getDropLabel()` and `getDropLabelIcon()`.
The latter one was already reported in #1018. So ideally, we need to fix all of those public APIs at once.

Here is how I would suggest to fix this:

1. Update the web component to initialise those 3 elements in corresponding `<slot>` elements instead of using the fallback content - this is how other components work, e.g. slotted pickers in case of `vaadin-date-time-picker`.
2. Make it possible for the web component to distinguish default components from the custom ones, and only apply `i18n` to the components that are initially created (including those that would be generated by `Upload` by default)
3. Update the `Upload` to create `Button` element during initialization, and do the same for drop label / drop label icon elements, and then make corresponding methods (e.g. `getUploadButton()`) return these instead of `null`.

This is a breaking change for styling, because we currently have `part="upload-button"` and `part="drop-label-icon"` in Shadow DOM on the `<slot>` fallback elements. Moving them to light DOM would force us to remove `part` usage.

**Comment by web-padawan** [comment]
See also #1284
