### ISSUE TITLE
Lumo theme: Dialog borders indistinct in dark mode

### ISSUE THREAD

**Issue by kkleinwi** [vaadin/flow-components#3600]
### Description

Dialogs in dark mode have very indistinct borders compared to light mode. This can be confusing to the user as it is not always visually obvious where the dialog's boundaries are.

Light mode dialog border using drop shadow:
![image](https://user-images.githubusercontent.com/6319035/184943033-475f9c16-5c90-4fee-b918-e3ad22c1b435.png)

Dark mode dialog border isn't clear:
![image](https://user-images.githubusercontent.com/6319035/184943158-07b2ae8b-df6f-4ae0-8e14-a7635bd98717.png)

### Expected outcome

Would like to see some style improvement so that dark mode dialog borders are more distinct.

### Minimal reproducible example

See attached screen shot snippets above.

### Steps to reproduce

View a dialog on top of other content in both light and dark modes.

### Environment

Vaadin version(s): 23.1
OS: Windows 10

### Browsers

Chrome

**Comment by jouni** [comment]
Can you verify that the `theme="dark"` attribute is on the `<html>`element, and not on the `<body>` element? That could explain the poor contrast.

<img width="1383" alt="Screenshot 2022-08-16 at 20 59 18" src="https://user-images.githubusercontent.com/66382/184947562-2935c1a5-1d28-403b-bc2c-cb4f82579546.png">

**Comment by kkleinwi** [comment]
We followed the example at the link below, so currently it's set on the <body> tag.
https://vaadin.com/blog/toggle-dark-lumo-theme-variant-dynamically

**Comment by jouni** [comment]
Right. Yeah, that tutorial is a bit incorrect in that part. The attribute needs to be set on the `<html>` element because that is the element where other custom properties that rely on the color props are defined.

If the `theme="dark"` attribute is set on the `<body>` element, those properties are not recomputed using the new colors, because they are only set from `<body>` downwards.

Unfortunately Flow doesn't offer a convenient API to manage the `<html>` element (or perhaps I’m not aware of one), so you need to resort to something like this:

```java
UI.getCurrent().getPage().executeJs("document.documentElement.setAttribute('theme', 'dark')");
```

**Comment by kkleinwi** [comment]
Tested that implementation and it works as expected. Thank you.
