### ISSUE TITLE
Grid selection doesn't change if selected items are removed from grid

### ISSUE THREAD

**Issue by INPUTsys-Chris** [vaadin/flow-components#3796]
### Description

It seems that the grid does not modify the selection state if selected items are removed.

If I select an item via UI and I have a button to remove the current selected item, then I see the item is removed from the grid, but the internal grid selection is not affected and a selection listener also isn't called.

Simpliest use case is enabling/disabling the remove button by using a grid selection listener. This doesn't work if UI/state is out of sync. Other more severe problems can be thought of.

### Expected outcome

Grid getSelectedItems should always return the current state, eg. never return items which were selected but removed previously.

Grid selection listeners should be called EVERY time the UI selection changes regardless if an item was selected/deselected or the item was removed from the data.

### Minimal reproducible example

```
@Route(value = "test")
public class TestGridSelectionUi extends VerticalLayout {

    private final Grid<Integer> grid;
    private final List<Integer> items;

    public TestGridSelectionUi() {
        setSizeFull();

        items = IntStream.rangeClosed(1, 10).boxed().collect(Collectors.toCollection(ArrayList::new));

        grid = new Grid<>();
        grid.addColumn(Object::toString);
        grid.setSelectionMode(Grid.SelectionMode.SINGLE);
        grid.setItems(items);
        grid.addSelectionListener(event -> {
            showNotification("SELECTION LISTENER. Selection now: " + grid.getSelectedItems());
        });
        Button selectFirstButton = new Button("Select first");
        selectFirstButton.addClickListener(event -> {
            grid.select(items.get(0));
            showNotification("Selected the first one programatically. Selection now: " + grid.getSelectedItems());
        });

        Button removeButton = new Button("Remove selected");
        removeButton.addClickListener(event -> {
            if (grid.getSelectedItems().isEmpty()) {
                return;
            }
            items.removeAll(grid.getSelectedItems());
            grid.getDataProvider().refreshAll();
            showNotification("Removed items. Selection now: " + grid.getSelectedItems());
        });

        add(selectFirstButton, removeButton, grid);
    }

    private static void showNotification(String item) {
        Notification notification = new Notification(item);
        notification.setDuration(3000);
        notification.open();
    }
}
```

### Steps to reproduce

In the example above
- select via grid click or button "Select first"
- Remove the selected item by button "Remove selected"
Notifications should reflect the current UI selection state.

### Environment

Vaadin version(s): 23.2, 14.8

### Browsers

Issue is not browser related

**Comment by INPUTsys-Chris** [comment]
Sorry, I don't think this is an enhancement.
getSelectedItems() returning values which are not present in the grid  can lead to serious problems.

I double checked in Swing and the behaviour is correct. dataModel.removeRow(...) leads to selection changes.  table.getSelectedRow() does NOT return items which are not in the grid any more.

**Comment by tomivirkki** [comment]
Hi, the Grid doesn't really know the full set of items the data provider has to offer. It's only aware of the subset of items it has received from the data provider as responses to data requests.

Let's say that instead of a `ListDataProvider` your Grid used a `BackEndDataProvider`, that lazily fetches items from a database (of millions of records). The user clicks some rows and items get selected. You then remove an item from the database and call `grid.getDataProvider().refreshAll();`. What happens now is that the grid simply empties its item cache and requests new items (from the data provider) for the currently visible page. If one of the previously selected items is no longer included on that page, Grid can't really know whether the item was actually removed or if it was just relocated to some other index and will emerge once the user keeps scrolling.

Another scenario. Let's say you have a previous selection state stored in the database and you apply it to Grid. One of the selected items could be on row 1000 so the Grid will only know that the item still exists once the user actually scrolls to that row. When that happens, the row will appear as selected, because the item is still included in the grid's selected items collection. If selected items could only include items that the grid knows of, then the state before scrolling to the item would be illegal, right?

One might argue that when a `ListDataProvider` is used, the full item set is actually available in the memory and could thus be used to automate such things as cleaning up the Grid's selected items. But from the Grid's point of view, both `ListDataProvider` and `BackEndDataProvider` are just `DataProvider`'s, regardless of the implementation details. It could also be unexpected if the behavior of `getSelectedItems()` worked differently based on which type of a data provider you use. Even with `ListDataProvider`, some users may not want to lose the selection state if they temporarily only show a subset of their full item set.

**Comment by INPUTsys-Chris** [comment]
@tomivirkki  Thank you for your detailed response!

I think your answer is centered about 2 aspects:
1. Avoiding corner cases
2. Simplicity

With that in mind, I understand and respect your decisions for the grid implementation. But as a developer I'm not convinced:

> Let's say that instead of a ListDataProvider your Grid used a BackEndDataProvider, that lazily fetches items from a database (of millions of records). The user clicks some rows and items get selected. You then remove an item from the database and call grid.getDataProvider().refreshAll();. What happens now is that the grid simply empties its item cache and requests new items (from the data provider) for the currently visible page. If one of the previously selected items is no longer included on that page, Grid can't really know whether the item was actually removed or if it was just relocated to some other index and will emerge once the user keeps scrolling.

Since a function is missing in DataProvider to detect if one item is present in the grid (when selecting programmatically or after refresh) I also think the grid for itself can't detect this currently. But every developer using selection and refreshAll() must implement that by itself, so there is not really a benefit:
- Developer must know selection contains items which are never present in the grid (grid.getSelectionModel().select("NotInGrid") is legal)
- Developer must work around that every time or extend the Grid class so that it doesn't return items which are not in grid
- Developer must know the selection listener is not coupled with the grid items and not called every time the real selection changes. This is not mentioned in eg. https://vaadin.com/docs/latest/components/grid/flow but the page contains this text:
> If you change the grid’s items with either setItems() or the used DataProvider, it clears the selection and fires a selection event. To retain the previous selection, reset the selection afterwards, using the select() method.

> Another scenario. Let's say you have a previous selection state stored in the database and you apply it to Grid. One of the selected items could be on row 1000 so the Grid will only know that the item still exists once the user actually scrolls to that row. When that happens, the row will appear as selected, because the item is still included in the grid's selected items collection. If selected items could only include items that the grid knows of, then the state before scrolling to the item would be illegal, right?

It's not about a grid knowing items, it's about a grid selection working so that as a developer I can assume:
- selection is about items in the grid
- selection listeners are called

For me, a grid selection is grid UI driven, not some kind of Set I put various items in. 

> One might argue that when a ListDataProvider is used, the full item set is actually available in the memory and could thus be used to automate such things as cleaning up the Grid's selected items

I expect ListDataProvider and BackEndDataProvider to work identically. Otherwise this would be a terrible DX.

> Even with ListDataProvider, some users may not want to lose the selection state if they temporarily only show a subset of their full item set.

I think that is actually a rare corner case:
- Showing a subset of data in grid
- Not using filter functions but settting entire list of items to a subset
- Expecting to not loose the selection

I don't expect you to change that behaviour and I understand your decisions but maybe my 2 cents help you to understand what problems the common developer faces.

Since I'm more or less the "extend and fix it" type of developer I will work around that in our code.

**Comment by tomivirkki** [comment]
> Since a function is missing in DataProvider to detect if one item is present in the grid (when selecting programmatically or after refresh) I also think the grid for itself can't detect this currently

If we added `DataProvider.hasItem(item)` or such API, which `Grid` would then use to every now and then check if it should remove something from its list of selected items, in the worst-case scenario it could be detrimental to performance. Let's say, in the case of your example above, removing the currently selected items, it's enough for the app logic to invoke `grid.deselectAll()` to have the items cleared. But if `Grid` was responsible for maintaining the list, I would have to check the status from the data provider, which in turn could result in multiple additional database queries.

**Comment by tomivirkki** [comment]
> If it's not the grid maintaining the real list of selected items, then I'm responsible. What would I do preventing, let's say, invalid items to be put in a cart? I also have to assure the selected items really exist in the DB.

Even if Grid automatically checked for the items, you would still need to write the implementation for the `dataProvider.hasItem(item)` method, right? There would not be any other way for Grid to check if the items exist or not. Well there is one: making a query for every item in the database.

So, if you anyway need to write the method implementation, then your app may as well use the same logic to check if the items are there or not (before placing them in the cart). If `Grid` would do this automatically for everyone, then every application would suffer from the performance hit. For example, every call to `grid.select(item)` would result in a database query because Grid would need to check if the item exists.

**Comment by INPUTsys-Chris** [comment]
Just found 
https://github.com/vaadin/vaadin-grid/issues/2099
and
https://github.com/vaadin/flow-components/issues/1059

I'll enter a comment about selection listeners in the DataView issue.
I guess we can close this discussion.
