### ISSUE TITLE
Multi-Select Grid reloads item details on selection change by grid.select()

### ISSUE THREAD

**Issue by mrgreywater** [vaadin/flow-components#3897]
### Description

When using a grid with multi-select enabled, the item details component is recreated whenever you change the selection using the java api `grid.select()` or `grid.asMultiSelect().updateSelection()`. Changing the selection by using the checkmarks works and does not force a item detail component recreation.

This is an issue, because the item details component may have changed due to user input, and just discarding that information is not required or expected.

### Expected outcome

When changing the selection programatically, just the selection changes, but the item details component stays untouched.

### Minimal reproducible example

```java
        grid.setSelectionMode(Grid.SelectionMode.MULTI);
        grid.setItemDetailsRenderer(new ComponentRenderer<>(() -> {
            System.out.println("Creating item details");
            return new Tabs(new Tab("A"), new Tab("B"));
        }));
        grid.addItemDoubleClickListener(e -> {
           grid.setDetailsVisible(e.getItem(), !grid.isDetailsVisible(e.getItem())); 
        });
        grid.setDetailsVisibleOnClick(false);
        grid.addItemClickListener(itemEvent -> {
           grid.select(itemEvent.getItem());
        });
```

### Steps to reproduce

Create multi-select grid with item details. 
Open Item Details using double click.
Change selection with checkboxes, notice item details component doesn't reload.
Change selection with `grid.select()`, notice item details component is recreated.

### Environment

Vaadin version(s): 23.2.4
OS: Windows 11

### Browsers

Chrome

**Comment by mrgreywater** [comment]
Thank you, I didn't know you could add an update callback for the component renderer. Even still, is it intended that if you select an item using the UI (by clicking the checkbox) no refresh of the item is issued? But if you call grid.select() it is? This inconsistency seems wrong.

**Comment by sissbruecker** [comment]
> Thank you, I didn't know you could add an update callback for the component renderer. 

Yeah, we might want to make that more obvious. Especially for column renderers that can add quite some overhead to recreate the DOM nodes every time when you do `grid.refreshAll`, so implementing an update function should be best practice and encouraged IMO. The current constructor signatures for component renderers maybe make it a bit too easy to implement it so that it has to recreate the DOM every time.

> Even still, is it intended that if you select an item using the UI (by clicking the checkbox) no refresh of the item is issued? But if you call grid.select() it is? This inconsistency seems wrong.

I just discovered the rerender-on-select mechanism today as part of another issue, and I can only assume that the purpose might be using the state as part of the rendering, or at least assume that some application already uses it in that way. Following that, the behavior should probably be aligned to refresh / re-render in both cases. I'll check back with the team, and then probably close this in favor of a new issue to align the behavior.
