### ISSUE TITLE
Clicking on the Icon of a Button or an Icon inside a Grid's ComponentRenderer the ItemClickListener of the Grid is also called

### ISSUE THREAD

**Issue by Dudeplayz** [vaadin/flow-components#4065]
### Description

I have a Button with only an Icon inside rendered inside a grid column. When clicking on the Icon, the Button's ClickListener and the Grid's ItemClickListener is called. If clicking on the text or the margin of the button, it works.
It was working in vaadin 14.x.

### Same issue for Icon

I could reproduce the same issue if the Button is replaced with an Icon with an added ClickListener.

### Expected outcome

Only the button's ClickListener is called.

### Minimal reproducible example

```kotlin
            val grid = Grid<String>()
            grid.addComponentColumn {
                Button("Test", VaadinIcon.LOCK.create()) {
                    println("Button Click")
                }
//                VaadinIcon.LOCK.create().apply {
//                    addClickListener {
//                        println("Icon Click")
//                    }
//                }
            }
            grid.addItemClickListener {
                println("Item Click")
            }
            grid.setItems("ABC", "DEF")
```

### Steps to reproduce

1. Click directly on the Icon of the Button
2. `Button Click` and `Item Click` should be in the console.
3. Clicking on the button's text
4. `Button Click` is in the console.

### Environment

Vaadin version(s): 23.1.3
OS: MacOS Ventura

**Comment by lbruun** [comment]
I wondered if the same thing happens if you had used a `LitRenderer`?  So I gave it a try.  Didn't make any difference.

I can fully replicate your issue.  I don't know why it works as expected (only the component's click event is fired) when the text or the background of the button is clicked, but why events fire when you click the icon inside the button.

Interesting: I tested out `ItemDetailsRenderer` because I assumed it would have the same issue as you are reporting with `ItemClickListener`. However, it doesn't:  When I click the icon inside the button - and I also have a `ItemDetailsRenderer`  - then only my button action is fired, not also the item details event.

**Comment by Dudeplayz** [comment]
@lbruun thanks for verifying the issue. Which version did you tested, because I am on an older one.

I think it's probably something related with the Icon, because the same behavior exists if only an Icon is used. Maybe the Icon prevents the "preventDefault" of the click event. And if clicking on the border or text of the button, the button component is responsible for being clicked, which handles this correctly.

Assumption (not sure): The DetailsRenderer is not affected by this, because if I am right, the click on the details is switching like a click on the row.

**Comment by lbruun** [comment]
I tested it with Vaadin Flow 23.2.5.

In html your button looks something like this:
```html
<vaadin-button ...>
    <vaadin-icon icon="vaadin:lock"></vaadin-icon>
    Lock
</vaadin-button>
```


I think it works with `<vaadin-button>` immediate content (like the text of the button) , but not for children (like `<vaadin-icon>`). Any children will inherit the click listener of the row too, while `<vaadin-button>` itself is immune to this.

**Comment by Dudeplayz** [comment]
I think the vaadin-icon is the problem, because if you use instead of the button an icon component and add a click listener, the same problem occurs. To test your assumption, you could add some child components to the button to see what happens. I can't test it self atm.

**Comment by lbruun** [comment]
> I think the vaadin-icon is the problem, because if you use instead of the button an icon component and add a click listener, the same problem occurs.

Well, I've tested with font icons, which means to use `<span>` (rather than `<vaadin-icon>`) and the same problem occurs there.

**Comment by TatuLund** [comment]
One possibility is to use event listener via element, so that you can add event data "event.stopPropagation()", so that click is not passed to the Grid,

```
        icon.getElement()
                .addEventListener("click", event -> Notification.show("Clicked"))
                .addEventData("event.stopPropagation()");
```

**Comment by Dudeplayz** [comment]
@TatuLund this workaround works, but I have to call the action in both listeners, because this also blocks the button from being clicked.

```kotlin
                val icon = if (isDetailsVisible(it)) VaadinIcon.ANGLE_UP else VaadinIcon.ANGLE_DOWN
                val iconCmp = icon.create().apply {
                    element.addEventListener("click") { _ ->
                        toggleDetails(it)
                    }.addEventData("event.stopPropagation()")
                }
                Button(iconCmp) { _ -> toggleDetails(it) }
```

**Comment by web-padawan** [comment]
We have some logic to ignore click events on focusable elements added in https://github.com/vaadin/flow-components/pull/4530/commits/6e5492768a4ab021aeb5d1405a7517a3beebbcf5:

https://github.com/vaadin/flow-components/blob/854b888caaf311766182406a8dba280bad157c95/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts#L1133-L1137

As you can see, it only checks `event.target` which means that for `<vaadin-button>` or e.g. regular `<button>` the `isFocusable(target)` will return `true`. However, for `vaadin-icon` component this code will return `false`.

IMO we should check that `event.composedPath()` doesn't contain a focusable element. This would fix the problem related to `vaadin-icon` inside `vaadin-button`. However, standalone `vaadin-icon` would still cause item click listener to fire.

Regarding a workaround: it's better to avoid using `.addEventData("event.stopPropagation()");` due to the problem above and instead use `.addEventData("event.preventDefault()");` - the [prevented click](https://github.com/vaadin/flow-components/blob/854b888caaf311766182406a8dba280bad157c95/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts#L1128-L1131) won't fire `item-click` event.
