### ISSUE TITLE
Investigate the feedback about the new validation behavior

### ISSUE THREAD

**Issue by vursen** [vaadin/flow-components#4167]
Let's inquire into the feedback we got about the new validation behavior to find out whether there are any issues that need to be fixed before enabling this behavior by default.

- https://github.com/vaadin/flow-components/issues/1158#issuecomment-1267592761

Related to https://github.com/vaadin/platform/issues/3066

**Comment by vursen** [comment]
Confirmed that there is an issue with committing an invalid input in date-picker when autoOpenDisabled. Created a ticket: https://github.com/vaadin/web-components/issues/5066

**Comment by knoobie** [comment]
I don't have time to test it properly, but an idea to be tested that it works: 

- You have a bean with a date property 
- You register the bean with a binder (using setBean) and mark this date field as required 
- User types a proper date and presses a save button: Expectation the server side date is stored and validation is successful 
- User changes the date to something unparseable like "Lorem" and presses save again: Expectation client side validation is failing AND the server side (already stored) representation is nulled so that the bean is also invalid

**Comment by vursen** [comment]
Thank you @knoobie for your input.

I tested DatePicker + Binder with this snippet:

```java
public static class Bean {
  private LocalDate value;

  public LocalDate getValue() {
      return value;
  }

  public void setValue(LocalDate value) {
      this.value = value;
  }
}

public DatePickerView() {
  Div value = new Div();

  DatePicker datePicker = new DatePicker("DatePicker");
  // datePicker.setAutoOpen(false);

  Binder<Bean> binder = new Binder<>(Bean.class);
  binder.forField(datePicker)
          .withValidator(date -> date.equals(LocalDate.of(2022, 1, 1)),
                  "Unexpected value")
          .withValidationStatusHandler(status -> {
              value.setText("Binder Value: " + status.getField().getValue());
          })
          .bind("property");

  Bean bean = new Bean();
  bean.setValue(LocalDate.of(2022, 1, 1));
  binder.setBean(bean);

  add(datePicker, value);
}
```

I can confirm that the value is correctly reset to `null` and the binder is properly notified _only as long as `autoOpen` is `true`._ 

When I set `autoOpen` to `false`, the value isn't reset and therefore the binder isn't notified either. This is exactly an issue that was reported above.

**Comment by knoobie** [comment]
Perfect! Thanks for confirmation!

**Comment by vursen** [comment]
Closing as https://github.com/vaadin/web-components/issues/5066 was fixed.
