### ISSUE TITLE
Vaadin 23.3: HasTooltip / Tooltip does not work properly

### ISSUE THREAD

**Issue by hoshie82** [vaadin/flow-components#4293]
### Description

I recognized, that there is a Tooltip implementation in the new Vaadin 23.3 Version... But it is not possible to use the HasTooltip  with own classes...  ?!
So why there is a difference in the logic between the interface and adding a tooltip to any component?! I want to use that interface in another button class I wrote... But a tooltip is only shown, if I use the  Tooltip.forComponent() call.

### Expected outcome

The tooltip should be visible, if it is used in other component classes, if the HasTooltip-interface is used...

### Minimal reproducible example

```
    private Component createContent() {
        CustomImage img1 = new CustomImage();
        img1.setSrc(new ThemeResource("img/image1.png"));
        img1.setTooltipText("123456789"); // DOES NOT WORK

        CustomImage img2 = new CustomImage();
        img2.setSrc(new ThemeResource("img/image2.png"));
        Tooltip.forComponent(img2).setText("abcdefg"); // DOES WORK

        return new VerticalLayout(img1, img2);
    }

    private static class CustomImage extends Image implements HasTooltip {

    }
```

### Steps to reproduce

... example shows bug

### Environment

Vaadin version(s): 23.3.0.beta2

### Browsers

Chrome

**Comment by web-padawan** [comment]
Thanks for the issue. We need to update the JavaDoc for `HasTooltip` interface to mention it doesn't work this way.
There are [examples](https://vaadin.com/docs/latest/components/tooltip) of using `Tooltip.forComponent` but no mention of `HasTooltip` there. Also, this is confusing:

https://github.com/vaadin/flow-components/blob/d0ffddd50f3e8e6ec6e56d82f13423400ee2e203/vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/HasTooltip.java#L20-L25

What we need to do instead is to explicitly state that this is an **internal** interface used by Vaadin components and it requires a component to apply JS logic an have proper DOM (`<slot name="tooltip">` in Shadow DOM) in order to work properly.
