### ISSUE TITLE
Fields with `setAllowedCharPattern` do not support some cases of removed `setPreventInvalidInput`

### ISSUE THREAD

**Issue by MathiasAugstein** [vaadin/flow-components#4307]
### Describe your motivation

Using a pattern like "[0-9]{1,10}" to restrict the input to maximum 10 digits worked for TextField::setPattern, but not for TextField::setAllowedCharPattern. The new method only seems to check if every part of the input string fulfills the pattern, which an e.g. 15 digit long number does in the above example. But Regex already provides a mechanism to match a pattern multiple times by encapsulating it in a capturing group.

### Describe the solution you'd like

setAllowedCharPattern should not check if all parts of the input fulfill the pattern, but if the whole input fulfills the pattern. Same  behavior as setPattern.

**Comment by web-padawan** [comment]
> setAllowedCharPattern does not allow invalid input at all. In my opinion setAllowedCharPattern 

Please note that `setAllowedCharPattern` intentionally requires a regular expression that matches a **single character**  to prevent typing invalid characters. We are not going to change this behavior, but we could probably document it better.

On the other hand, `setPattern` is just a shortcut for the native `<input>` element logic (although we also implemented it for `TextArea` using custom logic, because in HTML, there is no support for `pattern` in `<textarea>` element).

**Comment by Legioth** [comment]
Does this mean that there might be an opportunity for a new feature that would show feedback in the same way as `setAllowedCharPattern` but do the validation based on the whole field content like `setPattern`?

**Comment by web-padawan** [comment]
We used to have `setPreventInvalidInput(true)` API, but it was badly broken by making it impossible to type anything with certain regular expressions - see #1143, #1635, #2986. The `setAllowedCharPattern` API was added to replace it.

**Comment by Legioth** [comment]
`setPreventInvalidInput` is indeed often problematic since it uses the same pattern both for incomplete values and for the final value. I could imagine there are cases where you want to have a more permissive full-value pattern while typing and a more strict one for the final value.

Regardless of that, there's at least a workaround for the issue mentioned in the original issue by using `setMaxLength(10)` to limit the size instead of relying on the pattern for that purpose.

**Comment by MathiasAugstein** [comment]
Thanks for the quick clarification. The workaround should be enough for most use cases, and a better documentation helps.

**Comment by Freeman656** [comment]
Hi,
I'm currently using setPreventInvalidInput method in my app and migrating to Vaadin 23/24, it's now impossible to get the same behaviour as before. My example is quite simple, we have a specific number pattern including thousand separator (\\d'?){0,5}.
I tried some combinason using the setPattern and/or setAllowedCharPattern, but none if them fits.
The user has to be able to enter either 99999 or 99'999, so the setMaxLength is not an option in this case.

Do you suggest another way of dealing with this case (without using validators of course) or can you consider un-deprecate this feature for the future versions ?

Regards,

**Comment by Freeman656** [comment]
Hi,
Any input on this issue ? The removal of this feature avoid us from migrating to version 24.
Is it possible to keep the setPreventInvalidInput method or at least keep a possibility to use it at a lower level ?
Thanks,

**Comment by sissbruecker** [comment]
As has been mentioned, `setAllowedCharPattern` is not intended as a complete replacement for `setPreventInvalidInput`. The main purpose of that was to restrict which characters the user is allowed to type into the field, which `setAllowedCharPattern` does a better job of. We did not introduce an alternative for preventing input if the full value does not match a specific pattern because that has a questionable UX, and we recommend using validation together with showing an error as user feedback instead.

I opened a PR for clarifying the purpose of `setAllowedCharPattern` in the JavaDoc. As this issue was about changing how `setAllowedCharPattern` works, which we do not intend to do, I'll close this as resolved. Feel free to open a new feature request for introducing a separate feature for preventing input if the full input does not match a pattern, as suggested here: https://github.com/vaadin/flow-components/issues/4307#issuecomment-1340943208.
