### ISSUE TITLE
[ComboBox] setInvalid has no effect when simultaneously setting enabled and required

### ISSUE THREAD

**Issue by lgf10** [vaadin/flow-components#4322]
### Description

A ComboBox is not displayed as invalid, when setting it to invalid while also changing it from _disabled_ to _enabled_ and from _not required_ to _required_.

### Expected outcome

The ComboBox is enabled, shows the required indicator, and is marked as invalid.

### Minimal reproducible example

```java
ComboBox<String> field = new ComboBox<>("Example");
field.setItems(Arrays.asList("a", "b", "c"));
field.setEnabled(false);
field.setErrorMessage("Error");

Button invalidate = new Button("Invalidate");
invalidate.addClickListener(event -> {
    field.setEnabled(true);
    field.setRequired(true);
    field.setInvalid(true);
});

Button disable = new Button("Disable");
disable.addClickListener(event -> {
    field.setEnabled(false);
    field.setRequired(false);
    field.setInvalid(false);
});

add(field);
add(invalidate);
add(disable);
```

### Steps to reproduce

1. Click the "Invalidate" button
2. ComboBox is required and enabled, but is not marked as invalid
3. Clicking the "Invalidate" button again marks it as invalid

### Environment

Vaadin version(s): 23.2.11 and 23.3.0.beta2
OS: Windows 10

### Browsers

Issue is not browser related

**Comment by sissbruecker** [comment]
Did give this a quick try. The problem here is actually that, despite the `setInvalid(true)` call, the web component is not marked as invalid (does not have a red background, required indicator is not red). As the component is not invalid it also doesn't show the error message. I'll modify the OP to reflect this.

**Comment by sissbruecker** [comment]
Tested this with these recent changes, which seem to fix the issue:
- https://github.com/vaadin/flow-components/pull/4323 (24.0)
- https://github.com/vaadin/flow-components/pull/4325 (23.3)
- https://github.com/vaadin/flow-components/pull/4340 (23.2)

As part of this fix `ComboBox` will internally validate whenever its value changes and:
- set itself to invalid when it is required and has no value
- set itself to valid when it is not required, or it is required and has a value

Note that we discourage trying to control the invalid state externally, since the component's internal validation may override it on value change. In this specific case, where there is only a required validation, it should be fine. For custom validation rules we recommend using `Binder` instead of manipulating the invalid state manually.

If you really need to control the invalid state externally in more complex scenarios, you can use a value change listener (which runs after the components internal validation), and override the invalid state there.

**Comment by sissbruecker** [comment]
Closing this as resolved, as all mentioned PRs have been merged.
