### ISSUE TITLE
Erratic behavior click-selecting rows clicking empty cells in Grid since 23.3.0

### ISSUE THREAD

**Issue by evanzel** [vaadin/flow-components#4363]
### Description

I tried version 23.3.0 of Vaadin flow and I have the following erratic behavior.
When a grid is in single select mode and there are cells with empty values, I can not _consistently_ click select a row clicking the cell with an empty value.  It does not even work 100% clicking cells with a value. it seems to sometimes miss a click.
Selecting with space has no problem.
There was not such a problem up to Flow 23.2.11

### Expected outcome

When I click select a row it should be selected, even if I click an empty cell.

### Minimal reproducible example

        Grid<Integer> grid = new Grid<>();
        grid.addColumn(Integer::intValue).setHeader("item");
        grid.addColumn((source) -> "").setHeader("empty");
        grid.setSelectionMode(Grid.SelectionMode.SINGLE);
        grid.setItems(IntStream.range(0, 100).boxed());
        add(grid);

### Steps to reproduce

click select a row clicking on a cell in the empty column.
It will work one time out of 10.
click select a row clicking on a cell in the item column.
It will work 9 times out of 10.

### Environment

Vaadin version(s): 23.3.0
I downloaded the code from https://start.vaadin.com/app and added the above code, so as not to have any side effects from my own code.

### Browsers

Issue is not browser related

**Comment by DiegoCardoso** [comment]
This seems to be a side effect of https://github.com/vaadin/web-components/pull/4257, where a `cell-focused` value is added to the cell `part` attribute. 

This makes this check on the `vaadin-grid-active-item-mixin.js` mistakenly returns the cell as a focusable element because the check here:

https://github.com/vaadin/web-components/blob/faa53375f0b5bd076c3862e63778a61f5638ca2f/packages/grid/src/vaadin-grid-active-item-mixin.js#L110-L114

More specifically this check `element.getAttribute('part') !== 'cell body-cell'` which should be updated to something like `element.getAttribute('part').includes('cell body-cell')`, similar to what has been made here:

https://github.com/vaadin/web-components/blob/32fa7ffe92259f9557f35835b83b2b7b9e2c3ca0/packages/grid/src/vaadin-grid-active-item-mixin.js#L114-L117

**Comment by web-padawan** [comment]
Fixed by https://github.com/vaadin/web-components/pull/5157. The fix will be included to the next `23.3.2` patch release.
