### ISSUE TITLE
Grid+RichTextEditor : rich text editor does not show value when first set up

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow-components#4551]
### Description

Please see attached minimal reproducible example. Only when I click the button can I see the text content of the RichTextEditor grid cells.

### Expected outcome

I would think the editor should show the content immediately, not only when refreshed though a button click.

### Minimal reproducible example

```
package com.example.application.views.main;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.richtexteditor.RichTextEditor;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;

@PageTitle("Main")
@Route(value = "")
public class MainView extends HorizontalLayout {
    public MainView() {

        Grid<Integer> grid=new Grid<>();
        grid.addColumn(Object::toString).setHeader("I");
        grid.addComponentColumn(i -> {
            RichTextEditor rte = new RichTextEditor();
            rte.asHtml().setValue("<h1>"+i.toString()+"</h1>");

            rte.setReadOnly(true);
            return rte;
        }).setHeader("Text");
        Integer[] issss= {1,2,3,4,5};
        grid.setItems(issss);

        Button button = new Button("Click me to work around display bug", e -> {
            Integer[] foo = {1,2,3,4,5};
            grid.setItems(foo);
        });


        add(grid, button);
    }
}

```

### Steps to reproduce

Use code above as a view, enjoy.

### Environment

Vaadin version(s): 23.3.4
OS: macOS latest

### Browsers

Chrome, Firefox

**Comment by tomivirkki** [comment]
The `ComponentRenderer`, uses a parent [container](https://github.com/vaadin/flow-components/blob/9c5d8123ae481f576f1619322664682f97c113ae/vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java#L50) for all of the rendered `Component` instances that get passed to the client. The container [gets added as a virtual child](https://github.com/vaadin/flow-components/blob/9c5d8123ae481f576f1619322664682f97c113ae/vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java#L166) to the owner component so it doesn't automatically appear in the DOM on the browser. The individual child components originally included in the container get picked to the DOM on demand, for example, to the `Grid` column cells, when you scroll the `Grid`.

Some Flow components add internal JS executions that access the Web Component public API and Flow runs the executions for virtual child components even if they haven't actually been placed in the DOM. This is typically fine. However, in certain cases, accessing the Web Component public API may internally end up accessing the shadow DOM, etc, but since the element isn't actually in the DOM yet, the shadow DOM / internal props such as `this.$` may have not yet been initialized and an error gets thrown.

It's debatable whether this should be fixed in the Web Components so that, for example, the following scenario wouldn't throw an exception:

```js
const rte = document.createElement('vaadin-rich-text-editor');
rte.dangerouslySetHtmlValue('<p>Some <b>bold</b> text</p>');
document.body.appendChild(rte);
```

The issue could also be fixed by appending the container to the owner as a regular child instead of a virtual child. As a consequence, there would be an additional hidden element in the DOM of the `ComponentRenderer` owners:


```html
<vaadin-grid-column>
  <div class="component-renderer-container" hidden></div>
</vaadin-grid-column>

<vaadin-combo-box>
  <div class="component-renderer-container" hidden></div>
</vaadin-combo-box>

<vaadin-virtual-list>
  <div class="component-renderer-container" hidden></div>
</vaadin-virtual-list>
```
