### ISSUE TITLE
Impossible to hide bottom navbar

### ISSUE THREAD

**Issue by simasch** [vaadin/flow-components#4878]
### Description

If I use addToNavbar(false, header), the navbar on the bottom is still there.:

![image](https://user-images.githubusercontent.com/593352/227894292-8b37ee87-7279-46f2-a8e4-39a5e8c72fef.png)

![image](https://user-images.githubusercontent.com/593352/227894334-8144c3b0-1556-4808-ba12-1edbcd449656.png)

### Expected outcome

Bottom navbar should be hidden

### Minimal reproducible example

See the code in the Description

### Steps to reproduce

See the code in the Description

### Environment

Vaadin version(s): 24.0.2

### Browsers

Issue is not browser related

**Comment by rolfsmeds** [comment]
Seems like a regression caused by applying `min-height` on the `navbar` part without excluding the bottom bar in https://github.com/vaadin/web-components/pull/5150, which prevents the bottom navbar from collapsing to zero height.

Fix: change selector to exclude `[part="navbar"][bottom]` from the selector where `min-height` is applied.

(Would be good to also add a visual regression test for mobile mode, if that's somehow possible.)

**Comment by simasch** [comment]
Any plans when this will be fixed?

**Comment by jouni** [comment]
A quick workaround:

`styles.css`:
```css
vaadin-app-layout::part(navbar) {
  min-height: 0 !important;
}
```

**Comment by simasch** [comment]
Thanks @jouni didn't thought about setting the height.
