### ISSUE TITLE
GridPro with an edit column doesn't refresh currently edited cell

### ISSUE THREAD

**Issue by vesanieminen** [vaadin/flow-components#5372]
### Description

GridPro with a custom DataProvider which overrides the com.vaadin.flow.data.provider.DataProvider#getId method with an id equivalency check does not properly refresh the edited cell.

https://github.com/vaadin/flow-components/assets/108755/0cd64ac8-f7f1-492a-befb-bc893fe7642b

### Expected outcome

The cell would refresh as it does normally.

### Minimal reproducible example

[gridpro_refresh_bug-example.zip](https://github.com/vaadin/flow-components/files/12394240/gridpro_refresh_bug-example.zip)

### Steps to reproduce

1. Run the project
2. Edit a name cell, and notice that it does not get updated immediately but requires an additional focus event to happen.

### Environment

Vaadin version(s): 24.1.5 (also in 23.3.13)
OS: Mac 12.6.6

### Browsers

Chrome

**Comment by yuriy-fix** [comment]
This issue has been added to the backlog priority queue for further investigation.

**Comment by ugur-vaadin** [comment]
I am not sure if this can be classified as a bug. The problem here is, by design, the update is done via the provided `ItemUpdater`. The intended use of the updater is to update that object based on the field value. The `refreshItem` call on item property change in `GridPro` depends on the object have been actually updated since that is how `refreshItem` works in general.  An approach to this can be to delegate the data refresh responsibility to the user as an alternative. If it is not viable to provide the update item for any reason, they can explicitly refresh the item via calling `refreshAll` or `refreshItem` with the updated item after updating the underlying data. The code could be something like this:

`grid.addEditColumn(Person::getName).setBackendUpdateMode(true).custom(editorTextField, this::itemUpdater);`

I think we need an agreement between the user and us regarding the responsibility of refreshing the data. We can automatically do that if the item updater is used as intended. If not, I think we need a way to know if the item is not going to be updated through the updater, but it will be updated in another way.

**Comment by ugur-vaadin** [comment]
A workaround to be able to use `refreshAll` in the item updater is to use it like this:
`UI.getCurrent().beforeClientResponse(this, e -> dp.refreshAll());`
