### ISSUE TITLE
 TreeGrid : Still wrong initial calculation of hierarchy column width (reopener of #5595 )

### ISSUE THREAD

**Issue by SonReimer** [vaadin/flow-components#5813]
### Description

In some situations the bug is still present.
Using the ShowCase in #5595 the bug can still be reproduced if it is extended by a navigating to another page by a button and navigating back by another button or putting two TreeGrids in the same view  and pressing refresh.

### Expected outcome

I expect the initial column soize to be calculated correctly.

### Minimal reproducible example

[example3.zip](https://github.com/vaadin/flow-components/files/13548933/example3.zip)

### Steps to reproduce

See description

### Environment

Vaadin version(s): 23.3.33
OS: Windows

**Comment by vursen** [comment]
Hey @SonReimer! I'm investigating your issue and will update you on my progress.

**Comment by vursen** [comment]
I can confirm the issue and it's only reproducible in 23.3

**Comment by vursen** [comment]
I rolled back the change by @tomivirkki locally and started investigating the issue from scratch.

Here are my findings from debugging in 23.3:

1. The connector incorrectly sets the grid's size to 0, overriding any initial value set by Flow:
https://github.com/vaadin/flow-components/blob/ac6aafa3018c9a0234bfd63f961879abcaa69a57/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts#L78

2. Due to the size being 0, the connector resolves the web component's initial request with an empty array:
https://github.com/vaadin/flow-components/blob/ac6aafa3018c9a0234bfd63f961879abcaa69a57/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts#L350-L353

3. The empty response [triggers](https://github.com/vaadin/web-components/blob/e185bd330b4c049d4063f4a343c6fd86b34d7a41/packages/grid/src/vaadin-grid.js#L544-L553) a recalculation of the column widths, which is skipped due to the absence of rows.

4. Later, `$connector.updateSize()` sets the correct size, triggering a new root request to the connector.

5. This time, the connector returns preloaded data.

7. During  the response processing, this [expression](https://github.com/vaadin/web-components/blob/e185bd330b4c049d4063f4a343c6fd86b34d7a41/packages/grid/src/vaadin-grid-data-provider-mixin.js#L367) incorrectly returns `false`, preventing the web component from triggering children requests.

7. The data response triggers a recalculation of the column widths again, and this time it proceeds.

8. During the recalculation, the virtualizer [gets flushed](https://github.com/vaadin/web-components/blob/e185bd330b4c049d4063f4a343c6fd86b34d7a41/packages/grid/src/vaadin-grid.js#L635-L637), which triggers children requests.

9. However, these requests are handled asynchonously, and the recalculation finishes on a partially loaded grid.

**Comment by vursen** [comment]
Here is an example showing that the problem can be reproduced with the pure web component in all versions:

```html
<script type="module">
  import '@vaadin/grid/all-imports';

  const grid = document.querySelector('vaadin-grid');

  grid.size = 0;
  grid.dataProvider = ({ parentItem, page, pageSize }, cb) => {
    // Return 0 items on the initial request to emulate step (1)
    if (grid.size === 0) {
      return cb([], 0);
    }

    const levelSize = parentItem ? 5 : 100;

    const pageItems = [...Array(Math.min(levelSize, pageSize))].map((_, i) => {
      const indexInLevel = page * pageSize + i;

      return {
        name: `${parentItem ? parentItem.name + '-' : ''}${indexInLevel}`,
        children: true,
      };
    });

    if (parentItem) {
      // Return child items asynchronously to emulate step (9)
      setTimeout(() => cb(pageItems, levelSize), 0);
    } else {
      cb(pageItems, levelSize);
    }
  };

  grid.expandedItems = [
    { name: '1' },
    { name: '1-0' },
    { name: '1-0-0' },
    { name: '1-0-0-0' },
    { name: '1-0-0-0-0' },
    { name: '1-0-0-0-0-0' },
  ];

  grid.size = 100;
</script>

<vaadin-grid item-id-path="name" width="400px" overflow="end right">
  <vaadin-grid-tree-column path="name" auto-width flex-grow="0"></vaadin-grid-tree-column>
  <vaadin-grid-column path="name" auto-width flex-grow="1"></vaadin-grid-column>
</vaadin-grid>
```

**Comment by vursen** [comment]
The fix is merged and will be available in the following upcoming versions:

- 24.4.0.beta1
- 24.3.7
- 24.2.12
- 23.4.0.beta2
- 23.3.34
