### ISSUE TITLE
GridContextMenu does not work with grid in multi-select mode

### ISSUE THREAD

**Issue by AdamBrowning** [vaadin/flow-components#5833]
### Description

When a grid is set in multi-select mode and uses a GridContextMenu with the gridContextMenu.setOpenOnClick(true) you cannot select anything in the grid.

### Expected outcome

Be able to select something in the grid.

### Minimal reproducible example

```java
Grid grid = new Grid<>();
grid.setSelectionMode(SelectionMode.MULTI);

GridContextMenu gridContextMenu = new new GridContextMenu<>(grid);
gridContextMenu.setOpenOnClick(true);
```

### Steps to reproduce

Try to select any item in the grid.

### Environment

Vaadin version(s):  24.2.6

### Browsers

Issue is not browser related

**Comment by javier-godoy** [comment]
Behavior in 24.1.16: right-clicking the checkbox selects the row AND displays the context menu
![grid-24 1](https://github.com/vaadin/flow-components/assets/11554739/df094c8b-163a-4114-b379-7dfd080580da)

Behavior in 24.2.6: right-clicking the checkbox displays the context menu, the row cannot be selected (rendering grid unusable with that combination of settings)
![grid-24 2](https://github.com/vaadin/flow-components/assets/11554739/c3f83f0b-0a0d-4c6a-bc0b-62c7d9377fff)

**Comment by yuriy-fix** [comment]
It seems to be a behaviour change that was not intended. However, the proper behaviour for this one is under question. We could consider suppressing context-menu left click on the selection column.

**Comment by rolfsmeds** [comment]
Personally I feel that a left-click context is inherently problematic. Very bad discoverability is just one of the issues with that approach, and I would generally recommend having a column with buttons that open the menu instead.

In addition to the selection column, it will also conflict with e.g. TreeGrid expand/collapse actions.

That being said, although it doesn't solve _all_ cases where a left-click context menu is problematic on the Grid, it would probably make sense to just disable the menu on the selection column.

**Comment by bwajtr** [comment]
I've investigated the issue and how to disable the context menu on the selection column, and the solution is unfortunately not that straightforward.

I’ve disabled the context menu for the selection column via modification of `com.vaadin.flow.component.grid.contextmenu.GridContextMenu#onBeforeOpenMenu`. In this case, the menu is not opened. However, the selection checkbox is still not checked on click. 

To explain why, we have to look on what has changed in latest Vaadin compared to 24.1. The reason for the changed behavior can be found in changes of `vaadin-grid-selection-column-base-mixin.js`:
* In Vaadin 24.1 the selection checkbox had a `click` event listener, that performed the selection and sent it over to the server.
* In the latest Vaadin this is now changed, and the checkbox performs the actual selection on the `checked-changed` event.

Unfortunately, in Flow, when a context menu is attached to the grid and is bound to the `click` event via `setOpenOnClick(true)`, the `checked-changed` is never fired for the selection checkbox, because the `click` event is stopped by the context menu handler (there is `e.preventDefault()` in  `contextMenuTargetConnector.js` → `openOnHandler`). The `e.preventDefault()` is always called, even if the context menu is disabled via `onBeforeOpenMenu`.

That `e.preventDefault()` is there for a good reason → when the context menu is opened via right-click, it prevents opening the default context menu of the browser.

So we cannot entirely remove it. However, it is currently not possible to get around it somehow. I currently have two solutions in mind, both are weird I think:

1. Stop propagation of the `click` event when fired on the selection checkbox. So the click event would never reach the context menu handler. But that might have a lot of unintended effects.
2. Do not call `e.preventDefault` in the context menu handler when `click` is used to open the menu... that improves left click behavior in the grid and restores the original behavior (both context menu is opened and checkbox is checked)

I'll prepare a PR for the second solution, because I think it's slightly better and we can then discuss if it's a good way to go or not...

**Comment by bwajtr** [comment]
During the implementation of the second solution, I've finally found a more elegant way how to disable the context menu over the selection column entirely (only when a left click is used to open the menu) -> therefore I'll prepare PR for it

**Comment by bwajtr** [comment]
Also one note: This issue is specific only to Flow usage of Grid. When you use Grid and ContextMenu as pure web-components, you have much more control over when the context menu can be opened or not. The code that would prevent the context menu from opening on the selection column can be implemented for example as follows:

```typescript

    ...

    protected override render() {
        return html`
            <vaadin-context-menu open-on="click"
                                 ${contextMenuRenderer(this.renderMenu, [])}>
                <vaadin-grid .items="${this.items}"
                             @click="${this.handleClick}">
                    <vaadin-grid-selection-column
                            id="grid-selection-column"></vaadin-grid-selection-column>
                    <vaadin-grid-column path="name"></vaadin-grid-column>
                </vaadin-grid>
            </vaadin-context-menu>
        `;
    }

    handleClick(e: MouseEvent) {
        // Prevent opening context menu on selection column
        let eventContext = (e.currentTarget as Grid).getEventContext(e);
        if (eventContext.column && eventContext.column.id === 'grid-selection-column') {
            e.stopPropagation();
        }
    }
```
