### ISSUE TITLE
Select field doesn't work after removing with keyboard shortcut

### ISSUE THREAD

**Issue by EasyMeow** [vaadin/flow-components#6148]
### Description

Hello! We are using Vaadin 24.3.6 in our project and found that the select field breaks after reattach if it has no items.

![image](https://github.com/vaadin/flow-components/assets/63020967/eff3e775-4abc-4dce-b0ab-c43c717e0ea3)
![image](https://github.com/vaadin/flow-components/assets/63020967/eb1b09cb-deca-4864-a2a2-ce41f8afa8f4)

### Expected outcome

Normal select field displays in UI.

![image](https://github.com/vaadin/flow-components/assets/63020967/d6305a02-9c3c-42be-b57a-3ddb9fc7e962)

### Minimal reproducible example

```java
@Route(value = "")
public class MyView extends VerticalLayout {
    Select<String> select = new Select<>();

    public MyView() {
        Button detach = new Button("Detach");
        detach.addClickListener(event -> {
            remove(select);
        });
        detach.addClickShortcut(Key.ESCAPE);

        Button attach = new Button("Attach");
        attach.addClickListener(event -> {
            add(select);
        });

        add(attach, detach, select);
    }
}
```

### Steps to reproduce

1. Click on select field
2. Press Esc button (It runs Detach button's click listener)
3. Click on Attach button

![reattach_field](https://github.com/vaadin/flow-components/assets/63020967/672cb073-1a10-4aa4-b288-bbbadcadf005)

### Environment

Vaadin / Flow version: 24.3.6
Java version: 17

**Comment by sissbruecker** [comment]
It's also reproducable when the select contains items. The issue seems to be related to the keyboard shortcut somehow, it works if you just click the buttons. 

One thing that's noticable is that the select actually stays open after pressing escape (testable by adding a `Thread.sleep` in the server callback), and is removed with the overlay being open. The issue also reproduces by using any other key for the shortcut. When clicking attach, it creates a new select element, which fails on this line because the overlay doesn't exist: https://github.com/vaadin/web-components/blob/08bf848b3284c1e4f4e74ae34b02874aaeb195d9/packages/select/src/vaadin-select-base-mixin.js#L174-L175.

**Comment by web-padawan** [comment]
Can be reproduced in the web component by using `<vaadin-select opened>` as overlay opens before `ready()`.
I'll see if the [tooltip workaround](https://github.com/vaadin/web-components/blob/8e5223bcb61a5561fd984db5d11b31a73ec98eaa/packages/tooltip/src/vaadin-tooltip-overlay.js#L46-L50) could be used by `vaadin-select` to set `owner` and `_overlayElement` properly.
