### ISSUE TITLE
Dialog listener should check if event is default prevented before sending it to server.

### ISSUE THREAD

**Issue by abdullahtellioglu** [vaadin/flow-components#6241]
### Description

I added `vaadin-overlay-outside-click` event listener to prevent the dialog from being closed in Copilot. However, event.preventDefault() does not work because it is not checked in 

```
 private void registerClientCloseHandler() {
        //@formatter:off
        getElement().executeJs("const listener = (e) => {"
                + "  if (e.type == 'vaadin-overlay-escape-press' && !this.noCloseOnEsc ||"
                + "      e.type == 'vaadin-overlay-outside-click' && !this.noCloseOnOutsideClick) {"
                + "    e.preventDefault();"
                + "    this.$server.handleClientClose();"
                + "  }"
                + "};"
                + "this.$.overlay.addEventListener('vaadin-overlay-outside-click', listener);"
                + "this.$.overlay.addEventListener('vaadin-overlay-escape-press', listener);");
        //@formatter:on
    }
```

https://github.com/vaadin/flow-components/assets/100126447/3a04fbf2-2c1c-4269-944d-aa9fab7ce75b

### Expected outcome

Event should not be sent to the server if it is defaultPrevented. Adding `e.defaultPrevented` condition to listener would solve the issue

### Minimal reproducible example

// view
```java
        Dialog dialog = new Dialog("Dialog ");
        dialog.setCloseOnOutsideClick(true);

        TextField textField = new TextField("Hello");
        dialog.add(textField);

        Button closeBtn = new Button("Hide dialog");
        dialog.add(closeBtn);
        dialog.open();
```
//in client
```typescript
document.documentElement.addEventListener('vaadin-overlay-outside-click', (e: Event) => {e.preventDefault();} , {
      capture: true,
    });
```

### Steps to reproduce

 - Create a dialog that has setCloseOnOutsideClick property true. 
 - Run the application.
 - Execute the script in the console.
 - Click on outside of the dialog on the page and you will have the same result. 

### Environment

Vaadin version(s): 24.4.0.alpha23
OS: 

### Browsers

Issue is not browser related

**Comment by vursen** [comment]
Would `stopImmediatePropagation()` work for you as a workaround?

**Comment by abdullahtellioglu** [comment]
It works, thanks

**Comment by vursen** [comment]
I'm not sure what benefits this proposal would provide to Flow users, since they are expected to control whether the dialog should close from the server-side. From this perspective, the only purpose of this check seems to be support for a workaround in Copilot.

It now seems to me that using `stopImmediatePropagation()` in the capture phase is actually a proper solution, as it ensures that no `vaadin-overlay-outside-click` listeners are be executed at all. This approach would also work for grid-pro which adds a `vaadin-overlay-outside-click` to exit edit mode and does not check for `preventDefault()`:

https://github.com/vaadin/web-components/blob/178d0e0f144b788ee0f4431f8d535f92d59c75cb/packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js#L324-L325

**Comment by sissbruecker** [comment]
Let's close this, we do not expect Flow users to use JS to prevent a dialog from closing, and as mentioned there's already a dedicated API for it. Besides we should not randomly remove events from being relayed to the server.
