### ISSUE TITLE
MenuBar SubMenuItems render the focus ring on hover

### ISSUE THREAD

**Issue by RSM-SLU** [vaadin/flow-components#6386]
### Description of the bug

The Bug is reproducible in the documentation.
1. Head to https://vaadin.com/docs/latest/components/menu-bar#open-on-hover
2. Hover over "Share" -> "On social media": No menu item (Facebook, Twitter, Instagram) has a focus ring
3. Now hover over "By email" first, then "On social media": Now "Facebook" has a focus ring

### Expected behavior

No focus ring should appear, even if a previous icon was hovered before.

### Minimal reproducible example

Reproducible in the official documentation, see description.

### Versions

- Vaadin / Flow version: 24, 23 (did not test earlier versions)
- Java version: 17 for my app, unknown for the documentation
- OS version: Windows 10
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by DiegoCardoso** [comment]
This issue is also reproducible in `ContextMenu`:

https://github.com/vaadin/flow-components/assets/262432/7be7913f-0561-4f9e-8e25-93df10f6334a

It happens because after a submenu is closed, the parent item receives the [focus here](https://github.com/vaadin/web-components/blob/6ff1635f7d1f5c387047bd4d9e20a5b30817760e/packages/context-menu/src/vaadin-contextmenu-items-mixin.js#L378) (_note that it didn't have the focus before, as hovering over elements do not change focus_). And then, the next time this item is expanded again, **as it now has the `focused` attribute**, the first item on the submenu will receive focus [from this call](https://github.com/vaadin/web-components/blob/6ff1635f7d1f5c387047bd4d9e20a5b30817760e/packages/context-menu/src/vaadin-contextmenu-items-mixin.js#L121-L122), which ends up [receiving the focus ring attribute here](https://github.com/vaadin/web-components/blob/6ff1635f7d1f5c387047bd4d9e20a5b30817760e/packages/a11y-base/src/keyboard-direction-mixin.js#L147).

It looks like the logic that defines whether the first item should get focused (and the focus ring) needs some change. Perhaps detect whether the submenu is being opened by mouse or keyboard, and only apply the focus ring on the latter?
