### ISSUE TITLE
ComboBox "addCustomValueSetListener" does not trigger event when custom value is cleared

### ISSUE THREAD

**Issue by MatthieuSKRZYPCZAK** [vaadin/flow-components#6442]
### Description of the bug

When using “addCustomValueSetListener” with a “ComboBox” in Vaadin 24.4.3, no event is triggered when the custom value in the “ComboBox” is cleared. This behavior prevents detecting the clearing of the custom value.

### Expected behavior

An event should be triggered by the “CustomValueListener” when the custom value in the “ComboBox” is cleared, allowing proper handling of this action.

### Minimal reproducible example

Java : 
```java
@Id("combo")
private ComboBox<String> combo;

combo.addCustomValueSetListener(event -> {
    filter(event.getDetail());
});
```

1. Type a custom value in the “ComboBox” => filter is triggered
2. Clear the content of the “ComboBox”=> nothing happened

### Versions

- Vaadin / Flow version: 24.4.3
- Java version: 21
- OS version: Windows 11
- Browser version: Chrome

**Comment by web-padawan** [comment]
The reason for this behavior is the fact that clearing the `input` element value in the web component does not dispatch `custom-value-set` event. The value change listener should still be fired as the `value` is [set to empty string](https://github.com/vaadin/web-components/blob/fab94595fd5e8c11c0709413251be92994a1daa9/packages/combo-box/src/vaadin-combo-box-mixin.js#L986-L991).

I'd say this works as intended, although we probably should document this case explicitly in the JavaDoc, because the existing comment doesn't mention "empty value" and it could be considered as "not matching existing items":

> Adds a listener for the event which is fired when user inputs a string value that does not match any existing items

**Comment by rolfsmeds** [comment]
The value change event won't fire if the previous value (before the custom value) was empty, since the custom value was never actual set as the combo's value.

What would actually solve this (and other use cases) properly would be for combobox to support setting a value that is not in the list (without actually adding it to the list implicitly either).

**Comment by rolfsmeds** [comment]
Ok so I just tried setting the custom value as the value of the combobox without adding it to the list, and it seems to work just fine.

So unless I'm missing something, the solution should be as simple as
1. In `CustomValueSetListener`, set the custom value as the combobox's value (after converting it to a bean of the combo's type, if needed)
2. Use `ValueChangelistener` to catch the clearing of that value

**Comment by rolfsmeds** [comment]
Closing as stale. Feel free to re-open if still valid.
