### ISSUE TITLE
Share code across multiple Flow components

### ISSUE THREAD

**Issue by pekam** [vaadin/flow-components#650]
It would be great to have a module for shared utilities and interfaces that are shared across the Flow component modules.

Currently the `vaadin-flow-components-shared` module contains only test-scoped utilities.

Example cases which would benefit from this:
- Set images to `MessageList` as stream resources, which otherwise needs to copy lots of code from `AvatarGroup` https://github.com/vaadin/vaadin-messages/issues/31
- Make `SlotHelpers` public https://github.com/vaadin/vaadin-flow-components/issues/649

**Comment by knoobie** [comment]
I was thinking about adding more HasXYZ interfaces to flow, but instead of increasing the complexity in flow, it looks like it would make way more sense to create them here in a shared module. 

The newly created HasAriaLabel, HasLabel and other flow HasXYZ would be a good fit for such a module. HasLabel wasn't really used in the past so it doesn't really feel like a breaking change and HasAriaLabel was just created by me. Moving them here, like grid component renderer seems like a good fit.

**Comment by knoobie** [comment]
@web-padawan Created a draft for it here https://github.com/vaadin/flow-components/pull/2320

**Comment by web-padawan** [comment]
Thanks, added a comment. We will discuss it with the team next week, probably on Tuesday during backlog grooming.

**Comment by sissbruecker** [comment]
This has been addressed as part of https://github.com/vaadin/flow-components/pull/3074 and https://github.com/vaadin/flow-components/pull/2320
