### ISSUE TITLE
DatePickerI18n reference date not respected

### ISSUE THREAD

**Issue by simasch** [vaadin/flow-components#6628]
### Description of the bug

If I create a DatePicker like this:

    DatePicker datePicker = new DatePicker();
    datePicker.setAutoOpen(false);

    DatePicker.DatePickerI18n datePickerI18n = new DatePicker.DatePickerI18n();

    DateFormatSymbols symbols = new DateFormatSymbols(getLocale());
    datePickerI18n.setMonthNames(Arrays.asList(symbols.getMonths()));
    datePickerI18n.setFirstDayOfWeek(1);
    datePickerI18n.setWeekdays(Arrays.stream(symbols.getWeekdays()).filter(s -> !s.isEmpty()).toList());
    datePickerI18n.setWeekdaysShort(Arrays.stream(symbols.getShortWeekdays()).filter(s -> !s.isEmpty()).toList());
    datePickerI18n.setDateFormats("dd.MM.yy");
    datePickerI18n.setReferenceDate(LocalDate.of(1970, 1, 1));
    datePicker.setI18n(datePickerI18n);

I would expect that when entering a date 01.01.20 this should result in 01.01.2020 but it's 01.01.1970

<img width="345" alt="image" src="https://github.com/user-attachments/assets/2a30c064-bc19-4d9b-af5e-4781d24a12ef">

### Expected behavior

Date should be 01.01.2020

### Minimal reproducible example

See above

### Versions

- Vaadin / Flow version: 24.4.11
- Java version: 21

**Comment by yuriy-fix** [comment]
The behavior you're seeing is due to how two-digit year formats are interpreted by the DatePicker component. 

Here’s the relevant part from the [documentation](https://vaadin.com/docs/latest/components/date-picker/date-formats#two-digit-year-formats):

```Two-digit years are interpreted as being within a one-hundred year range whose midpoint is called the reference date. For example, a reference date of 2000-01-01 means that the date entered is interpreted as being within the range 1950-01-01 to 2049-12-31. Given that parameter, the year 50 is parsed to 1950 while 49 is parsed to 2049.```

When you set the reference date to `1970-01-01`, it means that two-digit years are interpreted as being within a range of `1920-01-01` to `2019-12-31`.

So when you input `01.01.20`, the DatePicker interprets 20 as 1920, because that year falls within the calculated range based on the reference date.

**Comment by simasch** [comment]
Hi @yuriy-fix 
Oh right 😅
Thanks for the clarification
