### ISSUE TITLE
Chart configuration is not restored on reattach

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow-components#6802]
### Description

The `chart.configuration` object gets cleared by the web component's `disconnectedCallback` but it doesn't get automatically restored on reattach. This manifests as an empty Chart.

https://github.com/user-attachments/assets/6ea53f7f-9f0c-4a75-8d2b-6691f7fde3ce

### Expected outcome

The chart configuration should get restored on reattach.

### Minimal reproducible example

Create a (hybrid) app with a Chart in one view, and some other view

### Steps to reproduce

- navigate to the view with Chart
- navigate to the other view
- navigate back to the view with Chart

### Environment

Vaadin version(s): 24.6

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment]
The problem is that chart configuration can be updated by calling many methods, mainly by [ProxyChangeForwarder](https://github.com/vaadin/flow-components/blob/main/vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/ProxyChangeForwarder.java#L95).
So far I don't have any ideas except that trying to store these calls somewhere and re-apply them on re-attach.
