### ISSUE TITLE
ComboBox web component with mandatory value keeps invalid state after valid value has been set

### ISSUE THREAD

**Issue by RhonanMS** [vaadin/flow-components#6881]
### Description

If a ComboBox that has a mandatory value (via setRequired(true)) receives an invalid value, it will keep the invalid state even after a valid value has been set. 

*Before a valid value is selected*
![before-valid-value](https://github.com/user-attachments/assets/7d0f3f22-4c4b-4fc9-ab89-6e7db710aff8)

*After a valid value is selected*
![after-valid-value](https://github.com/user-attachments/assets/e87c6284-1527-4393-b86c-5fa978572473)

### Expected outcome

I would expect the ComboBox to lose its "invalid" state after a valid value has been selected.

### Minimal reproducible example

```java
final Div value = new Div();

ComboBox<String> cb = new ComboBox<>();
cb.setItems(List.of("1", "2", "3"));
cb.addValueChangeListener(event -> {
	value.setText("Value: " + cb.getValue());
});
cb.setValue("");
cb.setRequired(true);

this.add(cb);
this.add(value);
```

### Steps to reproduce

1. Add snippet above to a view
2. Set a valid value from the ComboBox value list (1, 2 or 3)
3. ComboBox keeps invalid state after valid value has been set

### Environment

Vaadin version(s): 24.5.6
OS: Windows, Linux
Browsers tested: Edge, Firefox

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment]
Looks like `setValue("")` is the reason as it sets the combo-box value to something unexpected:

<img width="411" alt="Screenshot 2024-12-06 at 15 16 34" src="https://github.com/user-attachments/assets/1da7d133-3d3b-4e60-950f-6e0e42c6ae93">

As the component has a value on initialization, it is validated by the web component and is considered invalid (as the `checkValidity()` checks for the actual input element value, not the `value` property of the web component).

As a workaround, it's possible to call `comboBox.setValue(null)` instead of `setValue("")` or just omit it.
