### ISSUE TITLE
Provide a method setDateFormat

### ISSUE THREAD

**Issue by dg0s** [vaadin/flow-components#911]
The vaadin-date-picker doesn't support date format based on text format pattern.
The only way to apply some date formatters is using  DatePicker#setLocale.
It is not possible to apply the mask dd-MM-yyyy (##-##-####).

Provide a DatePicker#setDateFormat.
```
DatePicker datePicker = new DatePicker();
datePicker.setDateFormat("dd-MM-yyyy");
```

**Comment by vlukashov** [comment]
Notes from an internal discussion:
 - This issue can be split into several:
   1. providing a Java (Flow) API
   2. providing a TypeScript (Fusion) API
   3. exposing a `setDateFormat` method through a i18n properties object
   4. exposing a `setDateFormat` method directly on a date-picker instance
   5. setting the date / time format on a single date-picker instance vs setting the date / time format globally for all date-pickers in an app
   6. providing a global i18n API to customise other locale-specific behaviour than only the date / time format
 - The scope of this particular GitHub issue would be only about the 1). and 4). from the list above, i.e. the Java (Flow) API for individual date-picker instances. This implies that the Flow connector for the date-picker component could bundle a library like date-fns. But not the web component itself would not bundle such library by default.
 - Other parts of the list above should be covered by separate GH issues
 - Regardless of how the locale-specific formatting is implemented, for the purpose of backwards compatibility the defaults (using the application locale) should not change

Please share your thoughts on this suggestion.

**Comment by mstahv** [comment]
From Flow developers PoV, it would be great if formatting/parsing patterns would behave as in, or as close as possible, as in, Java. Didn't check date-fns, but that just popped on my eye. If its pattern format leak to the Java API, I hope it is similar to the one in JDK.

In Vaadin 8 there is an easy to use extra hook to parse the date time string on the server-side when the client can't do it.

**Comment by rolfsmeds** [comment]
They are very similar -- JDK has a few that date-fns is missing, and date-fns has a lot that JDK doesn't. There might be some details that are different, but the 80% most used patterns seem to be identical to me: https://date-fns.org/v2.21.2/docs/parse

It's also possible that we'd provide a server-side parsing option later as a separate feature.

**Comment by vaadin-miki** [comment]
As for server-side parsing, that would probably require serious rewriting, as currently client expects server-called methods to be returned asynchronously, whereas the component itself does not want that. I tried that in https://github.com/vaadin-miki/super-fields/issues/64 - to quote my comment:

>  @ClientCallable methods return a promise, whereas formatting / parsing methods on the client assume a value instead.

**Comment by hfazai** [comment]
+1

**Comment by chkpnt** [comment]
+1

**Comment by chkpnt** [comment]
It's a pity I'm unable to use 0-prefixed months and days for a German locale. :-/

Don't know if we need to have a Java-like `setDateFormat` as suggested, we could also go the other way around and provide an Java-API which is more similar to the JavaScript-API and allows to set the options passed on to the `toLocaleDateString(...)`. 

So if something like
```java
datePicker.setLocale(Locale.GERMANY);
datePicker.setLocaleDateStringOptions(YEAR_NUMERIC, MONTH_2_DIGIT, DAY_2_DIGIT);
```
ends up in `rawDate.toLocaleDateString("de-DE", { year: "numeric", month: "2-digit", day: "2-digit" })`,
that would be sufficient for me.

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat

**Comment by chkpnt** [comment]
Oh, just noticed the `Enhanced DatePicker` above. Work's for me 👍 

But I recommend to reword the JavaDoc for `setPattern(...)` to make it more transparent, that the passed on pattern is different from the pattern the Java developer might be familiar with from `SimpleDateFormat`.

**Comment by rolfsmeds** [comment]
The API design for this feature is currently being finalized but the plan is to add the following setter to `DatePickerI18n` object:

`public void setDateFormat(String dateFormat, String... parseFormats)
`
Where the 1st format param will be used both for parsing and displaying the value, and the additional format strings provided in the array param will be used for parsing if parsing fails on the first format.

**Usage example:**
```
DatePickerI18n datePickerI18nObj = new DatePickerI18n();
datePickerI18nObj.setDateFormat(“dd.MM.yyyy”, “dd/MM”, “yyyy-MM-dd”);
datePicker.setI18n(datePickerI18nObj);

```

**Comment by chrisw73** [comment]
> The API design for this feature is currently being finalized but the plan is to add the following setter to `DatePickerI18n` object:
> 
> `public void setDateFormat(String dateFormat, String... parseFormats) `
> Where the 1st format param will be used both for parsing and displaying the value, and the additional format strings provided in the array param will be used for parsing if parsing fails on the first format.
> 
> **Usage example:**
> 
> ```
> DatePickerI18n datePickerI18nObj = new DatePickerI18n();
> datePickerI18nObj.setDateFormat(“dd.MM.yyyy”, “dd/MM”, “yyyy-MM-dd”);
> datePicker.setI18n(datePickerI18nObj);
> ```

Seriously? WTF? A DatePicker is ALWAYS i18n! Why having another DatePickerI18n ?!?
setDateFormat ist a basic feature that's simply missing in the current implementation.
Just implement it, I do not see, why it did not already happen, or is this just a thnig to bug developers to switch to Vaadin Prime....!?!

**Comment by rolfsmeds** [comment]
Calm down, @chrisw73, DatePickerI18n is already today the i18n API for DatePicker, so the plan is to add this feature to the already existing i18n API. There's nothing commercial about that, it's part of the core component.

If your app needs to support multiple locales, you probably want to define all i18n properties in one place, and easily apply them to each DatePicker instance. By having the formatting defined in the i18n obejct, together with all translation strings and other locale-specific properties, you can define that once and apply it to each DatePicker instance. Otherwise you'd have to apply BOTH the i18n object AND the formatting separately each time.

**Comment by chrisw73** [comment]
@rolfsmeds - sorry. Just to explain myself: I am a REALLY long term Vaadin fan and since the API Changes after Vaadin 7 I see tings always going down the drain. Soryy ;-).

But I understand teh approach now. You want to develop this similar to UploadI18N. I see. Would not have been my favorite approach, but as long as it is consistent with the other api it it absolute okay for me :-).

Will it be part of latest Vaadin 14 LTS or just Vaatin 20/21?

**Comment by rolfsmeds** [comment]
No worries, @chrisw73, I know that migrations from V7 have been anything but easy.

We are also looking into improving the i18n functionality in the platform overall, to make it easier to do app-level localization instead of per-instance, but that's going to be a later improvement.

The custom format support is coming to V22 first, but will probably be backported to V14 as well sometime after that.

**Comment by FollowSteph** [comment]
For us being able to select the formatting is very important because we have customers who will sometimes use formatting such as Jan 1, 2021 as well as 01/01/2021 and so on. Being able to offer multiple dates was a big request for us and it's one of the bumps encountered when upgrading from Vaadin 8 to Vaadin 14.
