### ISSUE TITLE
Reading a bean in a read-only binder with a html rich text editor binding does not fill the editor with the value

### ISSUE THREAD

**Issue by thomasdewaelheyns** [vaadin/flow-components#97]
When a rich text editor in html mode is used with a binder in read only mode, the value from the bean is not loaded to the rich text editor in the UI.

Vaadin version: 14.3.1

Code to reproduce:
```
RichTextEditor richTextEditor = new RichTextEditor();
add(richTextEditor );
Binder<HtmlRichTextBean> binder = new Binder<>();
binder.forField(richTextEditor.asHtml()).withNullRepresentation("").bind(HtmlRichTextBean::getText,HtmlRichTextBean::setText);
binder.setReadOnly(true);
binder.readBean(bean);
```
This might be related to issue vaadin/vaadin-rich-text-editor-flow#91

**Comment by alvarezguille** [comment]
Fixed in https://github.com/vaadin/vaadin-rich-text-editor/pull/141 included in vaadin-rich-text-editor [1.2.1](https://github.com/vaadin/vaadin-rich-text-editor/releases/tag/v1.2.1) and vaadin [14.3.2](https://github.com/vaadin/platform/releases/tag/14.3.2).
Please comment or reopen if it can be reproduced.
